### ISSUE TITLE
Assignment2Q4

### ISSUE THREAD

**Issue by rennmela** [BME1478H/Winter2020class#11]
Do you have any tips for question 4?

**Comment by RayNele** [comment]
@moonj94 You want to make a comparison between the folders you copied and the original to make sure all of them are present

listing all the directories is not a comparison. If you make a list of all the directories that are NOT present, that would be a comparison.

**Comment by moonj94** [comment]
by the  folders you copied, you mean question 1 right? and I just want to be clear directories refers to folders right?

**Comment by RayNele** [comment]
>Help her compare the list of all the folders across the main computer and the hard drive.
> by the folders you copied, you mean question 1 right? 
Yes, you are comparing the folders that were copied over with the originals. 

> I just want to be clear directories refers to folders right?
yup

>Are we meant to assume that certain folders are missing?
No, but you are meant to write code that would be able to determine if folders are missing. Imagine there are 50,000 folders, and Meg has copied over 49,978 of them over. Write something for her that can determine which ones she is missing. 

If no folders are missing (which they shouldn't be if you did q1 correctly), then your solution will tell you (in some way shape or form) that no folders are missing.

**Comment by janehs** [comment]
Where are the folders in the main drive? Are they all in, for e.g., Documents? Or are they all over the place, e.g. some in Desktop and some in Documents, and we have to look in directories for subdirectories?

**Comment by RayNele** [comment]
@janehs they are all located in the same folder. The folder that you downloaded from quercus. You are comparing these with the folders that you copied over to make sure they are all present

**Comment by janehs** [comment]
Is there a certain path to the external hard drive we should be using?

**Comment by RayNele** [comment]
@janehs Wherever you downloaded or moved the downloaded directories, as well as wherever you copied it to should be fine.

I imagine most people have the directory tree like so:

```
~/desktop
│   your-file
│   your-file    
│
└───assignment-data
│   │   
│   │   
│   │
│   └───20180204-01
│       │   1.jpg
│       │   2.jpg
│       │   ...
│   
└───dir-you-created-for-this-assignment
│   │   
│   │   
│   │
│   └───20180204-01
│       │   data01.eeg
│       │   data02.eeg
│       │   ...
```

If you have something different, that is fine. 
less concerned about the paths, and more on how you decided to solve the problem

**Comment by rennmela** [comment]
Would the following output be sufficient?
Only in 20180204-01: .DS_Store
Only in 20180204-01: 1.jpg
Only in 20180204-01: 2.jpg
Only in 20180204-01: notes.txt
Only in /users/melanierenn/desktop/assignment-data/data-analysis/20180204-01: notes20180204.txt

**Comment by joelostblom** [comment]
@rennmela Note that the question asks you to compare which folders are missing, not the files within the folders.
