### ISSUE TITLE
A5, Part 1: No output

### ISSUE THREAD

**Issue by chowd505** [BME1478H/Winter2020class#110]
```python
# import libraries used in this script

import sys
import numpy 

def main():
    # read in the data from the .csv passed to our script
	filename = sys.argv[1]
	experiment_data = numpy.loadtxt(filename, delimiter=',')

    # store the command-line arguments that represent the start, stop, and step size in the variable rate_params
	rate_params = np.arrange(0.1, 1, 0.1)
    # note: since the parameters that are read by sys.argv are strings, we have to convert them to floats using float(a_string)
	range_rate = np.arange(float(rate_params[0]), float(rate_params[1]), float(rate_params[2]))

    # define a function that calculates mean squared error
def squared_error(prediction, data):
	residual = prediction - data
	mse = (residual**2).mean()          
	return mse

    # try the parameters and choose the one with the smallest squared error
mse = []
    # note two modifications below: we are taking the N0 and the time vector from data
N0 = experiment_data[0]
t = np.linspace(0, 10, len(experiment_data))
for r in range_rate:
	prediction = N0*np.exp(r*t)
	mse.append(squared_error(prediction, experiment_data))

best_fit = range_rate[np.argmin(mse)]
print('We predict the rate of growth of this bacterial population to be', best_fit)
    
    
# write the code necessary to make sure the main() function is called when we run the script from command line
if __name__ == '__main__':
	main()
```

I tried to run the above txt file. However, it does not return any output. 
Can you help me fix the code?

**Comment by joelostblom** [comment]
Could you let us know how you are running the code? Is it from command line or as a cell in a Jupyter notebook? If I paste your code in a notebook cell and run it I get `NameError: name 'experiment_data' is not defined`, which makes sense since that variable is not defined in the chunk you posted, do you get the same or are you executing any other code before this chunk?

**Comment by chowd505** [comment]
I am sorry. 
yes it give the error message - NameError: name 'experiment_data' is not defined. 

I am running it from command line.

how do I fix the code?

**Comment by joelostblom** [comment]
It is related to the indentation of your code. Currently, `experiment_data` is defined inside your `main()` function, but you are trying to use it outside, so Python will try to access it before it is defined. Have a look at the indentation from the sample code in the assignment (pasted below), where you can see that experiment is defined and accessed at the same level of intentation.

```python
# import libraries used in this script
**(a, 1 mark)  ....**

def main():
    # read in the data from the .csv passed to our script
    filename = **(b, 0.5 marks)...**
    experiment_data = **(c, 0.5 marks)...**

    # store the command-line arguments that represent the start, stop, and step size in the variable rate_params
    rate_params = **(d, 0.5 marks)....**
    # note: since the parameters that are read by sys.argv are strings, we have to convert them to floats using float(a_string)
    range_rate = np.arange(float(rate_params[0]), float(rate_params[1]), float(rate_params[2]))

    # define a function that calculates mean squared error
    def squared_error(prediction, data):
        residual = prediction - data
        mse = (residual**2).mean()          
        return mse

    # try the parameters and choose the one with the smallest squared error
    mse = []
    # note two modifications below: we are taking the N0 and the time vector from data
    N0 = experiment_data[0]
    t = np.linspace(0, 10, len(experiment_data))
    for r in range_rate:
        prediction = N0*np.exp(r*t)
        mse.append(squared_error(prediction, experiment_data))

    best_fit = range_rate[np.argmin(mse)]
    print('We predict the rate of growth of this bacterial population to be', best_fit)
    
    
# write the code necessary to make sure the main() function is called when we run the script from command line
**(e, 1 mark)...**
```

**Comment by chowd505** [comment]
> It is related to the indentation of your code. Currently, `experiment_data` is defined inside your `main()` function, but you are trying to use it outside, so Python will try to access it before it is defined. Have a look at the indentation from the sample code in the assignment (pasted below), where you can see that experiment is defined and accessed at the same level of indentation.
> 
> ```python
> # import libraries used in this script
> **(a, 1 mark)  ....**
> 
> def main():
>     # read in the data from the .csv passed to our script
>     filename = **(b, 0.5 marks)...**
>     experiment_data = **(c, 0.5 marks)...**
> 
>     # store the command-line arguments that represent the start, stop, and step size in the variable rate_params
>     rate_params = **(d, 0.5 marks)....**
>     # note: since the parameters that are read by sys.argv are strings, we have to convert them to floats using float(a_string)
>     range_rate = np.arange(float(rate_params[0]), float(rate_params[1]), float(rate_params[2]))
> 
>     # define a function that calculates mean squared error
>     def squared_error(prediction, data):
>         residual = prediction - data
>         mse = (residual**2).mean()          
>         return mse
> 
>     # try the parameters and choose the one with the smallest squared error
>     mse = []
>     # note two modifications below: we are taking the N0 and the time vector from data
>     N0 = experiment_data[0]
>     t = np.linspace(0, 10, len(experiment_data))
>     for r in range_rate:
>         prediction = N0*np.exp(r*t)
>         mse.append(squared_error(prediction, experiment_data))
> 
>     best_fit = range_rate[np.argmin(mse)]
>     print('We predict the rate of growth of this bacterial population to be', best_fit)
>     
>     
> # write the code necessary to make sure the main() function is called when we run the script from command line
> **(e, 1 mark)...**
> ```

**Comment by chowd505** [comment]
Thanks. 
I was able to fix the codes. 
However, I was wondering for the rate_params, the code should be np.arrange(0.1,1,0.1) or np.array(0.1,1,0.1)?

Which one will be right?

please advise.

**Comment by joelostblom** [comment]
Good that it solved :+1: 

Regarding `arange` vs `array`, it depends on which values you want to test:

```
In [3]: np.arange(0.1, 1, 0.1)
Out[3]: array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
```

```
In [5]: np.array([0.1, 1, 0.1])
Out[5]: array([0.1, 1. , 0.1])
```

**Comment by chowd505** [comment]
> Good that it is solved 👍
> 
> Regarding `arange` vs `array`, it depends on which values you want to test:
> 
> ```
> In [3]: np.arange(0.1, 1, 0.1)
> Out[3]: array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
> ```
> 
> ```
> In [5]: np.array([0.1, 1, 0.1])
> Out[5]: array([0.1, 1. , 0.1])
> ```

so does that mean, either using arrange or array is right for this assignment?

**Comment by joelostblom** [comment]
The comment above this line in the [assignment sample code](https://q.utoronto.ca/courses/136149/assignments/294623) read:

> store the command-line arguments that represent the start, stop, and step size in the variable rate_params

You can see from the output above, or from reading the help text of the two functions, that only one of them meet this criteria (I can't tell which one since it is part of the assignment for you to understand which function is relevant here).
