### ISSUE TITLE
A5, Part 1 - does not convert string to float error

### ISSUE THREAD

**Issue by parmoonsarmadi** [BME1478H/Winter2020class#111]
![Screen Shot 2020-02-20 at 4 00 48 PM](https://user-images.githubusercontent.com/59670331/74978455-a0a02280-53fa-11ea-876a-a20973f6a680.png)

I keep getting this error indicating that the conversion from string to float is not working. 

I'm wondering if it's necessary to use sys.argv[0]? 

I also keep getting an error saying "-f not found"

Not sure what's wrong here. Please help! Thanks in advance.

**Comment by parmoonsarmadi** [comment]
![Screen Shot 2020-02-20 at 4 01 17 PM](https://user-images.githubusercontent.com/59670331/74978675-2754ff80-53fb-11ea-86a5-e9620ac32ce8.png)

**Comment by joelostblom** [comment]
This sounds like the same error as reported in #88. Could you try the solutions suggested there, particularly [this comment ](https://github.com/BME1478H/Winter2020class/issues/88#issuecomment-586802059) and let us know if that solves your issue?

**Comment by joelostblom** [comment]
Please reopen if you're still experiencing this issue.
