### ISSUE TITLE
Jupyter notebook with answers to lecture challenges?

### ISSUE THREAD

**Issue by VeraPieters** [BME1478H/Winter2020class#116]
Prof Garton is referring to a jupyter notebook on Quercus with the answers to all the challenges from the lectures, but I haven't been able to find this. Can you explain me where to find this?

**Comment by RayNele** [comment]
Hey @VeraPieters, I don't think it's up yet. I'll bring this up with the TAs. Sorry about that

Can we address this @BME1478H/course-developers?

**Comment by SaraMati** [comment]
yes, sorry, I'll update the notebook to have the answers in a few hours

**Comment by RayNele** [comment]
Thanks @SaraMati

**Comment by VeraPieters** [comment]
Thanks both!
Will I be able to find it in quercus under Files/Week6?

Op vr 21 feb. 2020 om 12:31 schreef Ryan Lee <notifications@github.com>

**Comment by lrncdg2020** [comment]
Good morning. Just checking in to see if the lecture challenge answers have been posted? I have not been able to locate them.

**Comment by SaraMati** [comment]
both the lesson.md and the pdf are now uploaded this time including the answers

**Comment by lrncdg2020** [comment]
That's great. Thank you!
