### ISSUE TITLE
Lesson 6, page 4, DLL load failed (python ../code/stats_02.py inflammation-01.csv)

### ISSUE THREAD

**Issue by lrncdg2020** [BME1478H/Winter2020class#118]
Good morning,
I typed in the command 'python ../code/stats_02.py inflammation-01.csv' and received the following output:

Traceback (most recent call last):
  File "../code/stats_02.py", line 2, in <module>
    import numpy
  File "C:\Users\gmcgi\Anaconda3\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Users\gmcgi\Anaconda3\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.

Question: Any advice on how to respond to the 'DLL load failed'?

**Comment by lrncdg2020** [comment]
![image](https://user-images.githubusercontent.com/59653928/75047313-8a46a500-5494-11ea-82c6-d24e1cbf9443.png)

**Comment by joelostblom** [comment]
Try was reported previously in https://github.com/BME1478H/Winter2020class/issues/77, try the solutions suggested there and let us know if it is working.

**Comment by lrncdg2020** [comment]
100%! Thank you. 

pip uninstall numpy

pip install numpy

Did the trick.

**Comment by lrncdg2020** [comment]
Appreciate the help!

**Comment by joelostblom** [comment]
Great to hear it's solved!
