### ISSUE TITLE
Lesson 6, No such file or directory

### ISSUE THREAD

**Issue by lrncdg2020** [BME1478H/Winter2020class#119]
This is likely a simple problem but I have not figured it out yet.

- I set up 'data' and 'code' folders under 'Project'
- The 12 inflammation csv and 3 small csv's are in 'data'
- stats_01.py and stats_02.py are in 'code'
- I am in the 'data' directory
- I type 'python ..cd/code/stats_01.py small-01.csv' and receive the following error:

$ python ..cd/code/stats_01.py small-01.csv
C:\Users\gmcgi\Anaconda3\python.exe: can't open file '..cd/code/stats_01.py': [Errno 2] No such file or directory

Question: How should I proceed to resolve this?

**Comment by RayNele** [comment]
`data` and `code` are in separate folders and you are in `data`

you want to access stuff in the `code` folder, so you need to be typing `../code/stats_01.py`

**Comment by lrncdg2020** [comment]
Oops. I made a mistake in my previous explanation. I did actually type ../code/stats_01.py (not ..cd/code/stats_01.py as I indicated above).

However, when I type ../code/stats_01.py I get the following:

$ python ../code/stats_01.py small-01.csv
Traceback (most recent call last):
  File "../code/stats_01.py", line 2, in <module>
    import numpy
  File "C:\Users\gmcgi\Anaconda3\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Users\gmcgi\Anaconda3\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.

I reported on this DLL problem in a previous comment. Not sure how to proceed to resolve it.

**Comment by joelostblom** [comment]
Closing this since you have reported the new issue in #118 (thanks for opening a new issue, it is easier to keep track when there is one problem per issue).
