### ISSUE TITLE
A5,Part1 No Output

### ISSUE THREAD

**Issue by DeMario96** [BME1478H/Winter2020class#130]
I think I entered the code correctly, unsure how to continue. Also the similar issue raised on this platform didnt help me much. Im using Notebook
![Screen Shot 2020-02-21 at 7 40 50 PM](https://user-images.githubusercontent.com/59748627/75082804-65c5e980-54e3-11ea-8882-35689db2c797.png)

**Comment by RayNele** [comment]
`If __name__ ...` statement should be on the outermost level of indentation. Ie. Dont indent it

**Comment by DeMario96** [comment]
Now Im getting this error 
![Screen Shot 2020-02-21 at 8 35 09 PM](https://user-images.githubusercontent.com/59748627/75083826-bccebd00-54e9-11ea-9686-40175f239545.png)

**Comment by RayNele** [comment]
You're not reading in the right file for experiment_data. 

review what your `filename` variable is set to and what file you want to be reading in

**Comment by DeMario96** [comment]
So I did change the '0' to '1' and I got the below error. Also I reviewed a similar issue and Im still kind of confused 
![Screen Shot 2020-02-21 at 9 01 17 PM](https://user-images.githubusercontent.com/59748627/75084344-8430e280-54ed-11ea-90f0-2f69031475d4.png)

**Comment by joelostblom** [comment]
This sounds like the same error as reported in #88. Could you try the solutions suggested there, particularly [this comment ](https://github.com/BME1478H/Winter2020class/issues/88#issuecomment-586802059) and let us know if that solves your issue?

**Comment by DeMario96** [comment]
Okay read the comment, completely understood the first 2 paragraphs. The first line in the last paragraph has me kind of confused .

**Comment by joelostblom** [comment]
Run the script from command line like this: `python script_name.py file_name.csv`. The comments on `rate_params` were specific to that poster's issue.

**Comment by DeMario96** [comment]
Im running it as a stand alone in the command line?inside the previous code?after the previous code?

**Comment by joelostblom** [comment]
Sorry I don't fully understand what you mean. I meant that you should take the code that you were previously running in the notebook and put it in a file, e. g. `script_name.py`. Then you can run this from the command line with `python script_name.py file_name.csv` (if you're in the same directory as the script and has put your csv file there also).

**Comment by DeMario96** [comment]
So export the ipynb file to py, save is as model_growth.py. And run a new code as python model_growth.py bacteria.csv in the command line. Is that what you're saying?

**Comment by RayNele** [comment]
Yes that's it.

Can't run ipynb files from command line

**Comment by DeMario96** [comment]
Okay it worked!Thank you for your help
