### ISSUE TITLE
A5 Part 1 Error

### ISSUE THREAD

**Issue by eowyn7** [BME1478H/Winter2020class#132]
I am getting this error when I run my code but I am not sure as to what it means and what I am to do.

![image](https://user-images.githubusercontent.com/59631118/75084221-b2fa8900-54ec-11ea-89ad-2be009cf8ece.png)

**Comment by eowyn7** [comment]
Here is my code.
![image](https://user-images.githubusercontent.com/59631118/75084244-e0dfcd80-54ec-11ea-9248-6023980a3ea8.png)

**Comment by joelostblom** [comment]
Remember that the first item in `sys.argv` is the name of the currently
running script. So when you assign it to `filename` and then try to read it
using `np.loadtxt()`, it is trying to read your python script rather than a
csv file.

**Comment by eowyn7** [comment]
Ohhhhh. I feel like an idiot. Thanks.

**Comment by joelostblom** [comment]
Haha, I often feel the same way when discovering errors in my code!
