### ISSUE TITLE
Assignment #2 How/where do we submit?

### ISSUE THREAD

**Issue by jaelee1204** [BME1478H/Winter2020class#14]
Pardon my ignorance if I missed it. How/where do we submit the assignment 2?

**Comment by SaraMati** [comment]
Please submit your assignments Via Quercus: under assignment tab

**Comment by azinamini** [comment]
> Please submit your assignments Via Quercus: under assignment tab.
> (for assignment 2: a file (e.g. text file) containing your scripts (properly comment your code to show which segment applies to questions 1 to 4)

Hey, is a ".rtf " doc file with all the commands and their output acceptable? as I would like to make my responses organized and easy to follow

**Comment by joelostblom** [comment]
Yes that is ok.
