### ISSUE TITLE
string to float error in jupiter but works fine in command line

### ISSUE THREAD

**Issue by Azzy-BME** [BME1478H/Winter2020class#140]
Hello,

My assignment works fine when I call it in command line but when I run it in Jupiter, it gives the error of not being able to convert string to float. Can you please help me understand this.

Thanks
Azzy

**Comment by RayNele** [comment]
Can you show an example of the error and your code?

**Comment by joelostblom** [comment]
Depending on the exact error, this could be the same as https://github.com/BME1478H/Winter2020class/issues/88. Please try the solution st here if you have the same issue or provide additional detail here.

**Comment by Azzy-BME** [comment]
@RayNele , Here is my code and the error in Jupiter
Code:
![image](https://user-images.githubusercontent.com/47275119/75116027-340f6880-5632-11ea-8049-58ab89634da1.png)

Error:
![image](https://user-images.githubusercontent.com/47275119/75116041-4a1d2900-5632-11ea-8fe3-698c213cfae6.png)

Result when I run it in anaconda command:
![image](https://user-images.githubusercontent.com/47275119/75116089-b4ce6480-5632-11ea-94f9-f035d67df4af.png)

**Comment by Azzy-BME** [comment]
@joelostblom according to #88, this is how it should work (ie it should only work through command line when the appropriate parameters are assigned). The error can't convert string to float just doesn't make sense which is why I'm curious.

**Comment by RayNele** [comment]
@Azzy-BME  that's working as intended. `sys.argv` doesnt work the way we want it to in jupyter.

if you try `sys.argv[1]` in jupyter, it returns a string, which you are then trying to convert to a float, which doesn't work.

**Comment by joelostblom** [comment]
@Azzy-BME Is it clear how this works? Can we close the issue?

**Comment by Azzy-BME** [comment]
Yup! Thanks. I'll close it now.
