### ISSUE TITLE
question 1 , assignment 5

### ISSUE THREAD

**Issue by fakharin** [BME1478H/Winter2020class#143]
Hi there, for question 1 on assignment 5, I ran the main code in python and saved the file as py. then I include both the bacteria and model_growth files in a folder in my desktop (assignment 5)

However when I call the function in bash terminal, I don't receive any output and it just simply goes to the next line. I have include the picture of my code in addition with the bash terminal commands for your review:
<img width="570" alt="the bash terminal" src="https://user-images.githubusercontent.com/59659481/75098737-4f299c00-5590-11ea-8e37-9eb2bb79238a.png">
<img width="975" alt="model_growth" src="https://user-images.githubusercontent.com/59659481/75098764-9ca60900-5590-11ea-9dca-91b48e262b48.png">
<img width="770" alt="folder" src="https://user-images.githubusercontent.com/59659481/75098767-9fa0f980-5590-11ea-9e78-3209084116e8.png">

**Comment by RayNele** [comment]
you have a space between the `'` and the `__ `of `'__main__'`

**Comment by fakharin** [comment]
thank you, it worked
