### ISSUE TITLE
Pushing repo to GitHub

### ISSUE THREAD

**Issue by Runner-H** [BME1478H/Winter2020class#152]
I added lines to dummy_story.txt, saved the document. Next I did
`git add Assignments/dummy_story.txt`
`git commit -m "added line to story"`
`
git removet-v
git fetch upstream
git merge upstream/master
`

it returns
 

> Already up to date.

`git push origin master`

it returns:

> remote: Permission to BME1478H/Winter2020class.git denied to Runner-H.
fatal: unable to access 'https://github.com/BME1478H/Winter2020class.git/': The requested URL returned error: 403

What is happening? Do I have the wrong repo that I copied?

**Comment by joelostblom** [comment]
You're trying to push to this repo rather than to your fork. Create a fork of this repo, push to to it, and then open a PR from your fork to this repo.

**Comment by joelostblom** [comment]
Closing this in favor of #156 where I have given more elaborate instructions.
