### ISSUE TITLE
Week 6 stats

### ISSUE THREAD

**Issue by Erikado4** [BME1478H/Winter2020class#157]
Hello,

I am trying to run the stats_03 script on the data files but I am unable to since it gives me this error:

![script error](https://user-images.githubusercontent.com/59775419/75268521-98166600-57c5-11ea-9228-5c1742c03f74.JPG)

and my stats_03.py is correctly written:

import sys
import numpy

def average_inflammation():
    script = sys.argv[0]
    for filename in sys.argv[1:]:
        print ('running ', script, 'for ', filename)
        data = numpy.loadtxt(filename, delimiter=',')
        for row_mean in numpy.mean(data, axis=1):
            print(row_mean)

if __name__ == '__main__':
    average_inflammation()

I can see there is a problem with numpy but I have no idea how to fix that.

**Comment by RayNele** [comment]
Try `pip uninstall numpy` followed by `pip install numpy`

**Comment by Erikado4** [comment]
It worked. Awesome! Thanks
