### ISSUE TITLE
Assignment 2 Q1

### ISSUE THREAD

**Issue by fatemehmolaei** [BME1478H/Winter2020class#16]
I don't know how to give command to move all the folders content into other folders. I tried a bunch of commands, but it gives error.

**Comment by RayNele** [comment]
Post screenshots of what you have tried or copy paste commands that you have tried, as well as their error. 

>I tried a bunch of commands, but it gives error.

does not give me enough information to help you

**Comment by fatemehmolaei** [comment]
I have another issue as well. I wanted first remove the jpg ones but it's not working as well :|
<img width="1440" alt="Screen Shot 2020-01-16 at 11 28 35 AM" src="https://user-images.githubusercontent.com/59659311/72543349-974bf500-3853-11ea-9412-b50f4a151472.png">

**Comment by RayNele** [comment]
the straight bar  `|` is called a pipe. It is not used for separating commands. 

`a | b` is not the equivalent of `a` + enter key + `b`

`a | b` uses the output of command `a`, and uses it as the input of command `b`. This is called piping.

If you want to separate commands, you can use the semicolon  `;`

Additionally, manually using `cd` and `rm` every file is not a valid solution. What if Meg has 50,000 folders?

**Comment by fatemehmolaei** [comment]
Okay, I dont know, I just stuck here. thanks
