### ISSUE TITLE
Assignment 5 - Part 1 no output

### ISSUE THREAD

**Issue by javadza4** [BME1478H/Winter2020class#168]
Hi! This is the code I have written for part 1 but it is not giving me an output when i type python growth_model.py 0 2 0.1 in my terminal. The other questions that were similar did not help me. Could you please explain to me what I am doing wrong? 

<img width="657" alt="Screen Shot 2020-02-26 at 8 22 28 PM" src="https://user-images.githubusercontent.com/59808921/75403444-c2574900-58d5-11ea-86d7-5a3f94f60609.png">

**Comment by joelostblom** [comment]
Try calling the main function instead of squared_error. I can elaborate
when I'm at my laptop.

**Comment by RayNele** [comment]
What @joelostblom means is call on `main()` instead of `squared_error()` since first of all, main contains all the lines required, from reading in the file to actually printing the output. And second of all, calling on `squared_error()` requires 2 arguments, `data` and `operation`.

**Comment by javadza4** [comment]
This is what it gives me when I call on main(). What does this mean?

<img width="885" alt="Screen Shot 2020-02-26 at 9 42 17 PM" src="https://user-images.githubusercontent.com/59808921/75407401-e5d3c100-58e0-11ea-8a01-f51c74484121.png">

**Comment by RayNele** [comment]
The second argument after `python` is the file with which your `model_growth.py` reads in, aka `sys.argv[1]` on line 7.

Since you typed `python model_growth.py 0`, it's looking for a file named 0. Hence 0 not found

**Comment by javadza4** [comment]
im really sorry but its still not working. This is the new updated code and the output it is giving me. 
<img width="740" alt="Screen Shot 2020-02-26 at 10 30 45 PM" src="https://user-images.githubusercontent.com/59808921/75409808-b83e4600-58e7-11ea-8be8-cd2505c5a5c2.png">
<img width="808" alt="Screen Shot 2020-02-26 at 10 30 36 PM" src="https://user-images.githubusercontent.com/59808921/75409810-b96f7300-58e7-11ea-8506-bd09ee287502.png">

**Comment by RayNele** [comment]
A function needs to have arguments after it with round brackets `()`.

`arange` is a function, and thus its following arguments need to be surrounded by round brackets and not square brackets. 

Square brackets should only be used to index a list.

**Comment by joelostblom** [comment]
No worries, you have just mixed up the brackets. Use `()` to call the `np.arange` function, not `[]`

**Comment by javadza4** [comment]
ok that is what i originally had but this is the error it gives me when i use round brackets 

<img width="759" alt="Screen Shot 2020-02-26 at 10 39 29 PM" src="https://user-images.githubusercontent.com/59808921/75410156-eff9bd80-58e8-11ea-8a71-7addfec01d99.png">

**Comment by joelostblom** [comment]
To troubleshoot that, print the type of the items in `sys.argv` and think about how you need to convert them to the accepted input types that `np.arange` needs.
