### ISSUE TITLE
Q about Sed and Diff , HW2 related

### ISSUE THREAD

**Issue by rezabasiri** [BME1478H/Winter2020class#18]
I found this piece of code ($ sed 's|/.*||') from googling and used it in my HW to answer a question but I don't know what ('s|/.*||') part means. Anyone care to explain it to me?

Also, from what I read online, ($ Diff -q) should only return the differences; however, in my version of bash (OSX) it still returns similarities "comm". Is there a different option or something else that needs to be done to only return the differences?

**Comment by joelostblom** [comment]
Note that you can use backticks <code>`</code> to format code.

To me it looks like you are remove `./` from the beginning of file names, is that correct? If so, the `|` is just a separator and the text in between is what to replace (`./`) and what to add there instead (nothing in your case since it is empty between the two last `|`. The `s` just indicates that you are using the search syntax with `sed`.

`diff -q` works as expected for me:

```bash
~/Downloads
$ cat test.md                                                                          
here here

~/Downloads
$ cat test2.md
herer
there

~/Downloads
$ diff -q test.md test2.md
Files test.md and test2.md differ

~/Downloads
$ diff test.md test2.md                                                                  
1c1,2
< here here
---
> herer
> there
```

**Comment by rezabasiri** [comment]
sorry I meant (diff -q) to compare subdirectories, not file contents. Can you try this as well?

**Comment by joelostblom** [comment]
For me, this behaves as expected, only listing files uniquely in one directory. Could you please post the the commands you are running and their output, similar to what I have done below.

```shell
~/Downloads/test-diff
$ tree
.
├── testdir
│   ├── test.md
│   └── test3.md
└── testdir2
    ├── test2.md
    └── test3.md

2 directories, 4 files

~/Downloads/test-diff
$ diff -q testdir testdir2
Only in testdir: test.md
Only in testdir2: test2.md

~/Downloads/test-diff
$ diff testdir testdir2                                                                                                                  1 ↵
Only in testdir: test.md
Only in testdir2: test2.md
```

**Comment by rezabasiri** [comment]
Here it is:
```bash
$ tree
.
├── DiffTest1
│   ├── Folder1TEST
│   │   └── Untitled.rtf
│   └── Folder2TEST
│       └── Text.rtf
└── DiffTest2
    ├── Folder1TEST
    │   └── Untitled.rtf
    └── Folder2222TEST

6 directories, 3 files
#DiffTest1(Folder1TEST > Untitled ,Folder2TEST > Text); DiffTest2(Folder1Test > Untitled ,Folder2222Test)

$ diff -q DiffTest1 DiffTest2
Common subdirectories: DiffTest1/Folder1TEST and DiffTest2/Folder1TEST
Only in DiffTest2: Folder2222TEST
Only in DiffTest1: Folder2TEST
```
Why is this still returns `Common subdirectories`?

**Comment by joelostblom** [comment]
That's because `diff` does not traverse subdirectories by default, if you add the recursive flag `diff -qr DiffTest1 DiffTest2` you will get the output you want. I agree it is is not immediately clear that this is the behavior to expect after reading the man page on the `-q` flag.

**Comment by rezabasiri** [comment]
Thanks...that solved it.
