### ISSUE TITLE
A6 Part1a No column named `co2_emissions`

### ISSUE THREAD

**Issue by yxwy51fns** [BME1478H/Winter2020class#186]
When I tried to subset the "co2_emissions" in the variable called "wolrd_subset", I got an error message that said "['co2_emissions'] not in index." 

I then checked the url link: https://raw.githubusercontent.com/BME1478H/Winter2020class/master/data/world-data-gapminder.csv, and I didn't see "co2_emissions" in any columns.

Thank you.

**Comment by bilalhsyed** [comment]
I think they meant "co2_per_capita".

**Comment by joelostblom** [comment]
Yes, it should say 'co2_per_capita', sorry about that!

**Comment by yxwy51fns** [comment]
I see. Thank you for the clarification.

**Comment by joelostblom** [comment]
This has been changed in the linked dataset so closing this issue

**Comment by bilalhsyed** [comment]
I'm not seeing a change in the linked dataset? Also, if you were to change it to "co2_emissions" now, everyone that has completed the assignment already would have to go back and edit their assignments.

**Comment by bilalhsyed** [comment]
@joelostblom

**Comment by joelostblom** [comment]
@bilalhsyed Sorry I meant to say that this has been changed in the **notebook** not the dataset.

**Comment by bilalhsyed** [comment]
Ok, thank you.

**Comment by linamnt** [comment]
Reopening for students with the same question.
