### ISSUE TITLE
Assignment 2 Files Missing?

### ISSUE THREAD

**Issue by georgeamatyas** [BME1478H/Winter2020class#2]
Hello,

The assignment 2 instructions are based on manipulating data in many folders ("Copy all the folders' contents..."), but the Assignment2_data folder on Quercus has no subdirectories. In other words, I can only find the data for one subject but the assignment requires analysis of data for multiple subjects. Do we have to create this extra data?

Thank you,
George

**Comment by BME1478H** [comment]
Hi George

Thanks for spotting this. The full set of directories is now uploaded to
Quercus.

All the best

Michael
