### ISSUE TITLE
GitBash Error

### ISSUE THREAD

**Issue by GMBCI2022** [BME1478H/Winter2020class#20]
I installed the BASH Shell, set up my Git account, installed the Atom text editor, set it as the default and get the following error in GitBash. I get the same error if I type the command into the GTI CMD (Deprecated). Can you advise me on what I am doing wrong?
![055735E9-8744-4836-81CE-76616F8DF788](https://user-images.githubusercontent.com/59653928/72578477-30a2f780-38a4-11ea-914f-cd9a975714c6.jpeg)

**Comment by RayNele** [comment]
Sara sent out an email with the solution to this exact problem, but it's basically a repeat of issue #1 . However, only the solution for Mac was posted there, so here is a recap for windows and git bash for anyone else wondering.

> Hi Everyone, 
for people with Windows, if you couldn't run Conda in your bash terminal 
please follow the instructions below (the pdf attached is the same instructions together with screenshots) 
open anaconda terminal (type Anaconda terminal in the windows start bar) 
type 'path' in the terminal and copy the directory for Anaconda3
(it should be something like this 'C:\ProgramData\Anaconda3')
go to system environment variables (by typing it in the start bar)
click on Environment Variables 
click on path variable to edit and add the directory you looked up for Anaconda3 (also add Anaconda3\Scripts), it should look like this (notice C:\ProgramData\Anaconda3 and C:\ProgramData\Anaconda3\Scripts added to the end of the path variable. The other lines are relevant for you, disregard them).
click ok and close
You should be able to run conda in your git bash now



As for problem two `core.editor has multiple values`, try this command before doing that `git config --global --unset-all core.editor`

For whatever reason there are multiple core.editor values and we can't replace multiple values with only one value: `atom --wait`, So we have to remove all core.editor values before continuing which is basically what the command above does. 

report back if that fixes the issue so I can close the ticket.

**Comment by GMBCI2022** [comment]
That worked perfectly. Thank you.

**Comment by RayNele** [comment]
Thank you. Problem solved and issue closed.
