### ISSUE TITLE
A5 Adding Pull Request URL to Submission

### ISSUE THREAD

**Issue by bilalhsyed** [BME1478H/Winter2020class#209]
Hello, how do we know we've correctly submitted the URL? It doesn't show up in the Submission Details tab.

**Comment by linamnt** [comment]
Hi @bilalhsyed it seems Quercus is not capable of accepting both. There is another assignmetn 5 - part 2 submission portal for the URL. As mentioned in the announcement, you may need to resubmit your .py file as it may have overwritten (the window is open again so will not be flagged as late)
