### ISSUE TITLE
A2Q4 - how to present solution

### ISSUE THREAD

**Issue by antbee-eng** [BME1478H/Winter2020class#21]
Is it an acceptable solution to print both the common and uncommon directories in both locations? For eg, printing something like this: "Common subdirectories: assignment-data/20180204-01 and testnew/20180204-01" for common directories, and then printing something like this: "Only in testnew/: test" if there are uncommon directores (in this case, I just made up the test directory to see if it would work).

**Comment by RayNele** [comment]
Sounds fine, as long as a comparison is made
