### ISSUE TITLE
Urgent! Assignment #5 - Pull Request URL

### ISSUE THREAD

**Issue by azinamini** [BME1478H/Winter2020class#210]
firstly, I have noticed that I am unable to both submit a .py doc and a website URL at the same time so when I view my final submission, only one shows up not both. 
secondly, I have submitted my completed final assignment before the initial deadline (March1st) but now due to resubmission, my submission has been tagged as "late".
p.s. I could not find the option to just add a URL and so the only option was resubmission whihc resulted in getting labeled as "late submission".

**Comment by linamnt** [comment]
Sorry for that, we didn't realize that it can only take one type of submission. I will send an announcement with updated instructions, and of course, you will not receive any late mark penalization.
