### ISSUE TITLE
A6 Starting issue

### ISSUE THREAD

**Issue by sareen7** [BME1478H/Winter2020class#220]
Hi! I have begun Assignment 6 and when I try to run the first cell (to start the assignment), I keep getting this message.

Kernel Restarting
The kernel for Desktop/Sareen/last_first_assignment6.ipynb appears to have died. It will restart automatically.

It happens every time and I can't continue on with the assignment as a result.

Thank you for your help!

**Comment by RayNele** [comment]
I've replied to your issue on email.

Split the cell into its individual lines and let us know exactly which line is causing the crash.

**Comment by joelostblom** [comment]
Issue solved via email.
