### ISSUE TITLE
Assignment 7, Task 6 - info on 'year' is missing and columns are not renamed

### ISSUE THREAD

**Issue by VeraPieters** [BME1478H/Winter2020class#225]
I am replicating the scatterplot in task 6 and I come across two problems:

1. I feel like we need some info on which 'year' the plot displays?
2. The mark breakdown specifies 'Renamed columns (0.25 marks)'. Tho the columns in the example plot are still named 'region = Americas' etc. Are we supposed to change those names to 'Americas' etc?

Thanks!

**Comment by linamnt** [comment]
Hi Vera,  Thanks for flagging this!
1. I will update the assignment instructions to include:
> Subset the data to only include rows from 2014
2. We meant rename the axes (x and y) so that they match.

**Comment by VeraPieters** [comment]
Thanks!
