### ISSUE TITLE
Assignment 6, 2e

### ISSUE THREAD

**Issue by Azzy-BME** [BME1478H/Winter2020class#228]
hello,

For this question, the column "co2_emissions" is null. The result of world_data['co2_emissions'] > 20 produces the following error.
![image](https://user-images.githubusercontent.com/47275119/75940946-66a03900-5e5c-11ea-92e2-083434aa8e09.png)

Could you please help me with this.

**Comment by sareen7** [comment]
Hi!

How was this solved? I noticed that the column name is co2_per_capita and not co2_emissions. How do we counteract this?

Thank you.

**Comment by joelostblom** [comment]
For reference to students finding this issue, it was responded to in https://github.com/BME1478H/Winter2020class/issues/186
