### ISSUE TITLE
Assignment 6 2d Empty data passed with indices specified

### ISSUE THREAD

**Issue by DeMario96** [BME1478H/Winter2020class#229]
Im getting this error when I run my code. Am I using an incorrect code?
![Screen Shot 2020-03-06 at 6 14 49 PM](https://user-images.githubusercontent.com/59748627/76129856-a7bc5880-5fd6-11ea-9c63-5d34b7ef3dab.png)
![Screen Shot 2020-03-06 at 6 15 08 PM](https://user-images.githubusercontent.com/59748627/76129868-af7bfd00-5fd6-11ea-8f8d-6e9058f4d1ed.png)

**Comment by joelostblom** [comment]
You have typed "world_data" one time too many. You are using the boolean expression to filter world_data, and then using the returned data frame to filter world_data again via `loc`.

**Comment by DeMario96** [comment]
world_data.loc[[(world_data['income'] > 50000) & (world_data['year'] == 2013)] , ['country', 'life_expectancy', 'child_mortality']]
now gives me the error  'IndexError: Item wrong length 1 instead of 39201'

**Comment by RayNele** [comment]
Basically it's asking you for a boolean list, and you gave it a list containing the boolean list.

`(world_data['income'] > 50000) & (world_data['year'] == 2013)` on its own without the square brackets is already a list. 
With `[(world_data['income'] > 50000) & (world_data['year'] == 2013)]`, you made a list of a list, which isn't an argument that `.loc` takes. 

You can fix this dropping the square brackets, thus making it not a list.
