### ISSUE TITLE
A2Q1: Trouble using "for" loop to access all folders 

### ISSUE THREAD

**Issue by shobnams** [BME1478H/Winter2020class#23]

**Comment by shobnams** [comment]
I am trying to use a "for" loop to look through all the folders in the assignment-data folder we were provided so that I can copy all the files (except for .jpg) into the new folder (Meg) I made in the assignment-data folder. However, I keep getting errors therefore leaving me to do this without a loop in which it works but then my script includes a lot of lines. In the image, I was trying to look at only two folders in the assignment-data folder to see if my script worked. I would really appreciate the help.
![image](https://user-images.githubusercontent.com/59714722/72625472-d8590d80-3916-11ea-8491-cec79d66cc89.png)

**Comment by joelostblom** [comment]
For the encircled example in the image, you have created a folder in the current directory called `Meg`, but in the loop you are trying to access a folder with that name in the parent directory, which is what `../` means. Change to `./Meg` or just `Meg` instead and it should work.

Also note that you can delete the text in the issue template and type your own text in the first message. Thanks for reading it and adding a good descriptive title to your question :+1:

**Comment by shobnams** [comment]
Thank you very much for your input. I tried to just write Meg and ./Meg but I am still getting the same error.
$ for i in 20180204-01 20180220-01; do
> cp *.eeg *.txt *.csv Meg
> done
cp: target 'Meg' is not a directory
cp: target 'Meg' is not a directory

**Comment by joelostblom** [comment]
Could you try copying without the loop? Both one and multiple files and let me know if it works. And can you post the output of `ls -l` in that folder

**Comment by RayNele** [comment]
Ah, the blue line blocked out the mkdir command so I sat there for a couple minutes wondering why you were getting that error message. Good catch @joelostblom

**Comment by joelostblom** [comment]
Confused me too at first =) still not sure if the directory was actually named `Meg` since we can't see it but `ls -l` should answer that.

**Comment by shobnams** [comment]
Sure @joelostblom I will give that a try. I'm so sorry @RayNele for the poor image.

**Comment by shobnams** [comment]
@joelostblom I tried your suggestion and it somewhat works. It takes up a lot of lines in my script because I need to do use "cd" to get into each of the folders (eg. 20180204-01) and I need to see which types of extensions are present in each of the folders. Also, if I do it without a loop, when I do ls -l, it doesn't seem to copy everything into the new folder. 

$ ls -l
total 8
-rw-r--r-- 1 mynam 197609  5 Jan 17 11:22 data01.eeg
-rw-r--r-- 1 mynam 197609  5 Jan 17 11:22 data02.eeg
-rw-r--r-- 1 mynam 197609  5 Jan 17 11:22 data03.eeg
-rw-r--r-- 1 mynam 197609  5 Jan 17 11:22 data04.eeg
-rw-r--r-- 1 mynam 197609  5 Jan 17 11:22 data05.eeg
-rw-r--r-- 1 mynam 197609 22 Jan 17 11:20 info.csv
-rw-r--r-- 1 mynam 197609 11 Jan 17 11:22 labnotes.ext
-rw-r--r-- 1 mynam 197609 11 Jan 17 11:20 notes20180204.txt

I tried it for the first two folders but not all of the .eeg from the second folder got copied and I think this may be because the file names are the same. Anyway around this situation?

**Comment by joelostblom** [comment]
Could you run `ls -l` in the folder where you were trying to run the for loop? I just want to see that there is a folder there and it was created properly.

**Comment by shobnams** [comment]
Do you mean in the new folder I created? I ran ls -l in the new folder I created. This is how I created the new folder. Sorry I changed the name to Analysis. 

mynam@Supriti-Laptop MINGW64 ~/Desktop/assignment-data
$ mkdir Analysis

**Comment by joelostblom** [comment]
Ok, does something like `cp 20180204-01/*.txt Analysis` work now?

**Comment by shobnams** [comment]
I will give it a try but then I don't do:

for i in 20180204-01 20180220-01; do ?

**Comment by shobnams** [comment]
I used this line 

$ cp 20180204-01/*.txt 20180204-01/*.eeg 20180204-01/*.csv Analysis 

to copy the files into the new folder but again I am having the same problem. Since the files names for the .eeg (data01.eeg data02.eeg, etc) are the same for the first two folders, not all the .eeg files from the second folder I try to copy from, works.

**Comment by joelostblom** [comment]
I see, if you want to preserve parent directories, you can use the `--parents` flag as [explained here](https://serverfault.com/questions/180853/how-to-copy-file-preserving-directory-path-in-linux).

**Comment by shobnams** [comment]
Thank you. I will give that a try.

**Comment by shobnams** [comment]
@joelostblom unfortunately it didn't work. Are there any other ways? Since this is affecting question 1, my question 4 will be wrong too.

**Comment by joelostblom** [comment]
@shobnams just checking since you closed the issue, did you solve your problem? If not can you show what went wrong in your latest attempts?

**Comment by shobnams** [comment]
Yes @joelostblom  I found another way to do question 1 and it worked. Thank you for checking.
