### ISSUE TITLE
A7, Task6 - duplicate data

### ISSUE THREAD

**Issue by Azzy-BME** [BME1478H/Winter2020class#233]
Hello,

Can you help me understand why I'm getting duplicate data points
![Assadi_Azadeh_plot](https://user-images.githubusercontent.com/47275119/76440066-afdc1580-6393-11ea-81bb-fe8c0f72386b.png)

sns.relplot(x='children_per_woman', y='years_in_school_women', hue='income_group', col='region', data=world_data_2014, estimator='sum', col_wrap=3)

Thanks

**Comment by sareen7** [comment]
Hi! I believe it should be estimator=None

Let me know if that works!

**Comment by Azzy-BME** [comment]
Thanks @sareen7 for the suggestion but it didn't work. I actually removed the estimator statement all together and still.

**Comment by RayNele** [comment]
@Azzy-BME can I see how you've defined `world_data_2014`

**Comment by Azzy-BME** [comment]
world_data_2014 = world_data.loc[world_data['year']>2013]

**Comment by RayNele** [comment]
I believe the question only asks for 2014. Your current definition would include 2015 and beyond as well.

**Comment by Azzy-BME** [comment]
Ah! Got it. I read it to be 2014 and on wards.
Thanks!
