### ISSUE TITLE
A7Q6 'num must be 1 <= num <= 0, not 1' Error 

### ISSUE THREAD

**Issue by DeMario96** [BME1478H/Winter2020class#235]
I'm seeing this error although I think my codes are correct.What should I do?

```python
world_data_2014 = world_data.loc[world_data['year'] == '2014'] 
sns.relplot(x = 'children_per_woman', y = 'years_in_school_women', hue = 'income_group', col = 'region', data = world_data_2014, estimate= None, col_wrap=3)
```

**Comment by RayNele** [comment]
What's the error?

**Comment by DeMario96** [comment]
num must be 1 <= num <= 0, not 1

**Comment by joelostblom** [comment]
A good first step is to check the data frame that you are trying to plot. In this case your dataframe is empty because you are comparing the year column of integers with a string `'2014'`.

**Comment by DeMario96** [comment]
I see where I went wrong, thank you !
