### ISSUE TITLE
Assigment 8 1.d

### ISSUE THREAD

**Issue by stefandenkovski** [BME1478H/Winter2020class#237]
I dont understand what you expect us to plot. 

Current have a dataframe that looks like this. 
![image](https://user-images.githubusercontent.com/55927104/76898812-c8a16b00-686c-11ea-9b93-5dd2820f802c.png)

 and it makes a plot like this, without me specifying the axis, but im not sure how i would since its a wide dataframe, i tried using melt but it didnt work. 

![image](https://user-images.githubusercontent.com/55927104/76902335-2a180880-6872-11ea-82ad-03417c8ec302.png)

Any advice would be helpful

**Comment by joelostblom** [comment]
You're not meant to plot the summary data frame, use the non-aggregated one instead.
