### ISSUE TITLE
Assignment 8, 1f and 2d,  Error in lineplot() and catplot() with kind='point', "Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'" 

### ISSUE THREAD

**Issue by antbee-eng** [BME1478H/Winter2020class#238]
Hi there,

In assignment 8, I am running into the same issue for two parts (task 1 f) and task 2 d) ). I am getting the following error when trying to use lineplot() and catplot() with kind='point': " Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe' ". I am simply plotting this data (ex: sns.lineplot(x='timepoint',y='BOLD signal',data=gammas) ).

This seems like a strange error and I've looked online and there may be issues with the version of numpy and seaborn (https://stackoverflow.com/questions/60060301/typeerror-cannot-cast-array-data-from-dtypeint64-to-dtypeint32-accordin ).

Please let me know if anyone has advice on this.

Thanks!

**Comment by joelostblom** [comment]
Hmmm, did you try the solution suggestion in the SO thread you linked? You should see the location of seaborn's algorithm.py in the traceback shown when the error is raised. Then you can edit that file directly as suggested in the SO reply and restart the notebook kernel to try the plot again.

**Comment by linamnt** [comment]
Given this will mostly be an issue on certain implementations/versions of numpy, as long as you are able to write the expected "correct" code, even if it does not output on your machine, we will accept the full marks. You can link to this issue in the comments of your submission for the marking TAs and  let them know as well just in case.
