### ISSUE TITLE
A.2, Q.4 Compare folders' contents or just the folder itself?

### ISSUE THREAD

**Issue by azinamini** [BME1478H/Winter2020class#24]
Hey, 
for Q.4 is it required to go through files within each folder or checking the folders alone is sufficient? for instance, let's say I will be comparing the folders which are the outcome of Q.1 with the original folders provided for this assignment, in this case no folder is missed per se but the content of the folders ( files in them) are missed sometimes. you do not expect us to answer this part of the problem, right?

**Comment by joelostblom** [comment]
You're right, the question only asks to compare the folders, not their contents.
