### ISSUE TITLE
Error question 3b

### ISSUE THREAD

**Issue by t-christ1** [BME1478H/Winter2020class#240]
This is my input: 

```python
world_data_2010 = world_data.loc[world_data['year'] == 2010]

top_education_ratio_2010 = world_data_2010.nlargest(5, ['education_ratio', 'country', 'year'])

# do not change the code below, write your answer code above
top_education_ratio_2010
```

The error I'm getting (just the end portion) says: "TypeError: Column 'country' has dtype object, cannot use method 'nlargest' with this dtype"

I'm not exactly sure how to change this - I've tried a bunch of different things

**Comment by RayNele** [comment]
>Display the five (5) largest education_ratio observations for the year 2010 in descending order (using dataframe.nlargest(number, column_name) where number is the number of observations to find) 

So the question only asks for `nlargest` of `education_ratio`. I would try to address this first. 

You're calculating `nlargest` for a bunch of columns. One of which is a text column consisting of names of countries. There isn't a way for pandas to figure out which country is largest so it just doesn't want to do it. 

>and only include the columns country, year, and education_ratio

So calculate `nlargest` for only the column we want `(education_ratio)`, and then only display the columns that we want. There are multiple ways of doing this, I'll let you try and figure it out. Let me know if you're stumped and I can drop another hint.

**Comment by RayNele** [comment]
@t-christ1 did this fix your problem?

**Comment by t-christ1** [comment]
Yes, thanks!

On Mar 20, 2020, at 10:12 AM, Ryan Lee <notifications@github.com<mailto:notifications@github.com>> wrote:



@t-christ1<https://github.com/t-christ1> did this fix your problem?
