### ISSUE TITLE
A8, 2a

### ISSUE THREAD

**Issue by eowyn7** [BME1478H/Winter2020class#241]
Why is this giving me a syntax error? I checked previous lectures and I cannot seem to find the answer.
![image](https://user-images.githubusercontent.com/59631118/77196599-0e9f3e80-6aba-11ea-8739-f3434b4cc9ae.png)

**Comment by RayNele** [comment]
You need to use `loc` or `iloc` when indexing both rows and columns

**Comment by eowyn7** [comment]
i tried that too and it gave me the same error

**Comment by RayNele** [comment]
Whenever you use `:` in indexing, the resulting output is always a list. Putting `[]` around a `:` is redundant since you're making a list of a list.

**Comment by eowyn7** [comment]
Got it, thanks
