### ISSUE TITLE
A9T2e) - df.melt two columns into alternating vs complete dissolution of first column, then the second

### ISSUE THREAD

**Issue by Shiroifuyuki** [BME1478H/Winter2020class#242]
This is the code I'm running:
```python
# 2e answer here
subset_melted = subset_2e.melt(id_vars=['country', 'year'], value_vars=['children_per_woman','child_mortality'])
subset_melted.sort_values(by=['country','variable'],inplace=True)
# keep this code here to check the result
subset_melted
```
Rather than getting this: 
![image](https://user-images.githubusercontent.com/31785185/77207557-0e11a280-6ad0-11ea-848e-5e9ed8c486bf.png)

I get something like this: 
![image](https://user-images.githubusercontent.com/31785185/77207571-1cf85500-6ad0-11ea-9870-046ff78a64cc.png)

As you can see, the example alternates between child_per_woman and child_mortality. In mine, both columns are there but they're dissolved block by block (all the child_per_woman is at the front, all the child_mortality is at the end). 

I tried resorting it by country, then by variable to artificially recreate whats going on in the image but Afghanistan exists so it still doesn't look like the image. Moreover, I have an index column which isn't given in the example image...

![image](https://user-images.githubusercontent.com/31785185/77209542-e53fdc00-6ad4-11ea-88e3-2861e4239af2.png)

I can't seem to find anything in the melt documentation [https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.melt.html#pandas.DataFrame.melt] that changes how the the columns are dissolved nor how to remove indices. I've tried drop, reset_Index, and so on. 

I'm on Win10, Python 3.7.

**Comment by joelostblom** [comment]
The melting operation you have performed is correct. The screenshot in the assignment is just there to illustrate that each country should occur twice, one time for each variable. I understand that it can be  confusing, so we will either add a clarifying sentence or remove the illustration from the assignment.

**Comment by linamnt** [comment]
Hi, as Joel mentioned, I just made an example to show you what the columns should have, it does not need to look exactly like the example I made. The instructions do not specify that you need to sort or anything, but I will remove the image as it is leading to confusion.
