### ISSUE TITLE
A8-2E - Interchangeable variable mappings to `hue` and `x` in the boxplot

### ISSUE THREAD

**Issue by John-BME** [BME1478H/Winter2020class#245]
Hi, 
For assignment 2e, we can plot it in two ways:
sns.boxplot(x='diet', y='pulse', data=running, hue='time')
sns.boxplot(x='time', y='pulse', data=running, hue='diet')
Which one is requested because the question doesn't clearly explained it?

**Comment by joelostblom** [comment]
I agree with you that it can be done in either of the ways you suggest and we consider them both correct. Since 2e is a follow up of 2d, I would be inclined to use the same variable mapping that you used there.
