### ISSUE TITLE
Assignment 8,3c 'Series' objects are mutable, thus they cannot be hashed

### ISSUE THREAD

**Issue by DeMario96** [BME1478H/Winter2020class#247]
This is the code I have been running
world_1800_2000 = world_data.loc(world_data['year'] == '1800') | (world_data['year'] == '2000')  
and I'm getting the error code 'Series' objects are mutable, thus they cannot be hashed

**Comment by RayNele** [comment]
You're missing a set of square brackets around the `loc` indices

**Comment by DeMario96** [comment]
Tried that already, when I do put them my table is empty in the output

**Comment by RayNele** [comment]
You've also set it to be `1800` as a string, but it needs to be an integer (without the single quotes)

**Comment by RayNele** [comment]
@DeMario96  did this fix your problem?

**Comment by DeMario96** [comment]
Problem fixed!Thank you
