### ISSUE TITLE
A8 3C No Output

### ISSUE THREAD

**Issue by DeMario96** [BME1478H/Winter2020class#249]
#247 continued 
I tried with and without the brackets previously and I'm still getting problems. With the square brackets I'm just getting no output as seen below 
![Screen Shot 2020-03-22 at 6 25 53 PM](https://user-images.githubusercontent.com/59748627/77262173-9cba2700-6c6a-11ea-9d51-82822d2619a9.png)

**Comment by RayNele** [comment]
I've answered back in #247, sorry for prematurely closing the issue.
