### ISSUE TITLE
Assignment 9, 2B

### ISSUE THREAD

**Issue by moonj94** [BME1478H/Winter2020class#250]
I am getting the error:
`'Series' object has no attribute 'pivot'`

in response to:
`world_data_decades1970_le = world_data_decades1970.groupby(['region','year'])['life_expectancy'].agg('mean')
world_data_decades1970_le.reset_index()

decades1970_pivot =  world_data_decades1970_le.pivot(index='region', columns='year', values='life_expectancy')`

**Comment by RayNele** [comment]
You used `.agg('mean')` method here instead of simply `.mean`.

`.agg('mean')` turns the object into a pandas Series, which you can't pivot.

`.mean` keeps it as a Dataframe

**Comment by moonj94** [comment]
I used .mean() and I still get the same error.

**Comment by joelostblom** [comment]
Continued in https://github.com/BME1478H/Winter2020class/issues/251
