### ISSUE TITLE
Assignment 9 2B

### ISSUE THREAD

**Issue by moonj94** [BME1478H/Winter2020class#251]
I keep getting the error 

`AttributeError: 'Series' object has no attribute 'pivot'`

When I apply the following lines:

```python
world_data_decades1970_le = world_data_decades1970.groupby(['region','year'])['life_expectancy'].mean()

world_data_decades1970_le.reset_index()

world_data_decades1970_le.head()`

decades1970_pivot =  world_data_decades1970_le.pivot(index='region', columns='year', values='life_expectancy')`
```

**Comment by joelostblom** [comment]
Don't forget to assign the data frame to a variable name after resetting the index, e.g.:

```
world_data_decades1970_le = world_data_decades1970_le.reset_index()
```

Currently you are just displaying the dataframe after resetting the index, so when you do `pivot` in the next line, you are still using the Series created from `mean` in your first line.

**Comment by moonj94** [comment]
Ohh of course. Thank you!
