### ISSUE TITLE
A9-2D

### ISSUE THREAD

**Issue by John-BME** [BME1478H/Winter2020class#252]
Hi, 
In the question of A9-2D, it is written "Set `margins=True` to draw the borders in each cell", but the margins=True add the median of each row as a "All" column in each cell and it seems is not related to set borders(?). Am I right or we should consider another modification?
Code is as follows:
decades1970_pivottable_median = pd.pivot_table(world_data_decades1970, values='life_expectancy', index=['region'], columns=['year'], aggfunc=np.median, margins=True)

Best, 
John

**Comment by joelostblom** [comment]
You're right that the phrasing is a bit odd. `margins=True` adds an aggregated column as you said. No need to consider any other operation.
