### ISSUE TITLE
A9 3a

### ISSUE THREAD

**Issue by Brendannigel** [BME1478H/Winter2020class#253]
Hello so I have this code here for the two new variables:

`le_asia_1970 = amer_asia_1970_2000.loc[(amer_asia_1970_2000['region']=='Asia') &
                                       (amer_asia_1970_2000['year']==1970), ['life_expectancy']]
le_amer_1970 = amer_asia_1970_2000.loc[(amer_asia_1970_2000['region']=='Americas') &
                                       (amer_asia_1970_2000['year']==1970), ['life_expectancy']]`

but when I go to the next cell to visualize the distribution of life_expectancy in the Asia/Americas in 1970 it outputs a blank plot with error `single positional indexer is out-of-bounds`

why is this happening? Thanks

**Comment by Brendannigel** [comment]
sorry the indentations will look wrong in what I have above but it looks like this 
![image](https://user-images.githubusercontent.com/59632050/77791160-8af6cc00-703c-11ea-8dde-d28b643a0ef5.png)

**Comment by RayNele** [comment]
duplicate #248
