### ISSUE TITLE
Have trouble opening Week 11 Lesson Notebook File

### ISSUE THREAD

**Issue by yizhouchen216** [BME1478H/Winter2020class#254]
Hello,

I had trouble opening the Week 11 Lesson notebook file. I am wondering if anyone else has this problem. My Jupyter Notebook can open other files as usual.

I got this while I tried to open the file
![image](https://user-images.githubusercontent.com/59633680/77802680-c8b21f80-7051-11ea-8cef-4b2b3f3b90f0.png)
 
Thanks,
Yizhou

**Comment by bilalhsyed** [comment]
I'm having the same problem here.

**Comment by Azzy-BME** [comment]
Same!

**Comment by RayNele** [comment]
It seems the wrong file was uploaded, we'll address this soon.

**Comment by linamnt** [comment]
Hi, I've just reuploaded the file, sorry about that, please let me know if there are still issues with the notebook!
