### ISSUE TITLE
Assignment 9-Can't print graph in 3a

### ISSUE THREAD

**Issue by Juniperberry-git** [BME1478H/Winter2020class#257]
# run this cell to visualize the distribution of life_expectancy in the Asia/America in 1970
sns.kdeplot(le_amer_1970, legend=False)
sns.kdeplot(le_asia_1970, legend=False)

I keep on getting an error when I try to run this code, I don't really understand what the error is. I got the previous question and the correct table for le_amer_1970 and le_asia_1979. Thanks for your help, 
<img width="842" alt="Annotation 2020-03-28 211417" src="https://user-images.githubusercontent.com/60361821/77837650-8fed7580-7139-11ea-8423-701ff24acca3.png">

**Comment by RayNele** [comment]
I have to see how you've defined the two datasets, could you post the code and the output?

**Comment by Juniperberry-git** [comment]
le_asia_1970 = amer_asia_1970_2000.loc[(amer_asia_1970_2000['year'] == 1970) & (amer_asia_1970_2000['region'] == 'Asia'), ['year', 'region', 'life_expectancy']]
le_amer_1970 = amer_asia_1970_2000.loc[(amer_asia_1970_2000['year'] == 1970) & (amer_asia_1970_2000['region'] == 'Americas'), ['year', 'region', 'life_expectancy']]

# run this cell to visualize the distribution of life_expectancy in the Asia/America in 1970
sns.kdeplot(le_amer_1970, legend=False)
sns.kdeplot(le_asia_1970, legend=False)

**Comment by RayNele** [comment]
@Juniperberry-git the question asks only for `life_expectancy` as a column

**Comment by RayNele** [comment]
ie: you have too many columns selected, one of which contains a string ('region') and kdeplot isn't built to plot strings. 

let me know if this solved your problem.

**Comment by Juniperberry-git** [comment]
So I changed the column to life_expectancy as the only on selected 

# 3a answer here 0.5 marks
le_asia_1970 = amer_asia_1970_2000.loc[(amer_asia_1970_2000['year'] == 1970) & (amer_asia_1970_2000['region'] == 'Asia'), ['life_expectancy']]
le_amer_1970 = amer_asia_1970_2000.loc[(amer_asia_1970_2000['year'] == 1970) & (amer_asia_1970_2000['region'] == 'Americas'), ['life_expectancy']]

But now I'm getting another error: IndexError: single positional indexer is out-of-bounds

**Comment by Juniperberry-git** [comment]
So actually I tried to reset the index for the le_asia_1970 and le_amer_1970 above, and now the plot works but there is a warning message that came with the plot. Is this OK
<img width="718" alt="Annotation 2020-03-29 110844" src="https://user-images.githubusercontent.com/60361821/77852668-e1cfe300-71ad-11ea-9157-1e337bd08fd8.png">

**Comment by RayNele** [comment]
You can fix this out of bounds error by following #248
