### ISSUE TITLE
A10 T3

### ISSUE THREAD

**Issue by Azzy-BME** [BME1478H/Winter2020class#258]
Hello,
can you help me understand why my prediction isn't Gaussian? 
![image](https://user-images.githubusercontent.com/47275119/77837891-87e30500-713c-11ea-84f4-2be5dfddfe97.png)

where: 
`x=world_data_2014['income']
y=world_data_2014['child_mortality']
le_model = sm.GLM(y, x, family=sm.families.Gaussian(link=sm.families.links.log()))

le_results = le_model.fit()`

Thanks

**Comment by bilalhsyed** [comment]
I think you forgot to add the constant term to x in Part a.

**Comment by Azzy-BME** [comment]
Thanks @bilalhsyed ! Appreciate it.
