### ISSUE TITLE
A10 Task 3 Error "Shape of passed values is (2, 6), indices imply (179, 6)"

### ISSUE THREAD

**Issue by coopboyd** [BME1478H/Winter2020class#261]
**Part a) code**

```python
x = world_data_2014.income
y = world_data_2014.child_mortality
x = sm.add_constant(x)

le_model = sm.GLM(y, x, family=sm.families.Gaussian(link=sm.families.links.log()))
le_results = model.fit()
# do not change the code below()
print(le_results.summary())x = world_data_2014.income
```

**Part b) code**
```python
sns.scatterplot(x, y, data=world_data_2014, label='data')
plt.scatter(x, le_results.fittedvalues, label='prediction')
plt.legend()
```
I keep getting this error message with this code.. If I remove the 'x = sm.add_constant(x)' from the code I then get a graph that looks like this (which I believe is wrong)... Any help is appreciated. Thanks.
<img width="573" alt="Screen Shot 2020-04-04 at 9 37 30 PM" src="https://user-images.githubusercontent.com/59628725/78464249-4f53a600-76bd-11ea-9f4a-15607ca8c67e.png">

<img width="388" alt="Screen Shot 2020-04-04 at 9 42 51 PM" src="https://user-images.githubusercontent.com/59628725/78464244-482c9800-76bd-11ea-999e-5731016dbaaf.png">

**Comment by joelostblom** [comment]
Change the line where you're defining `le_results`:

```diff
-le_results = model.fit()
+le_results = le_model.fit()
```

Currently, you're using a variable called `model` which you have defined somewhere outside the code you pasted above.

**Comment by joelostblom** [comment]
And remember that when you call `sns.scatterplot`, you should supply the column **names** of the data frame **as strings**. You are currently providing it with two separate pandas Series (x and y), which works here but could give you headaches down the road so make sure to use strings of the column names instead.

**Comment by coopboyd** [comment]
Thank you!
