### ISSUE TITLE
Ass10-2d-double check

### ISSUE THREAD

**Issue by John-BME** [BME1478H/Winter2020class#263]
Hi,
I just want to have a very quick double check with you. For Ass10, Task 2d, is the following and the attached graph, the correct one you request:

```python
sns.lmplot('child_mortality', 'life_expectancy', hue = 'income_group', data=world_data_2014)
```

![Ass10-Task 2d](https://user-images.githubusercontent.com/26355187/78508759-49aa9e80-7757-11ea-8469-c9e782f279ff.jpg)
I look forward to hearing from you soon.

**Comment by pantufa** [comment]
got exact same output but am also not 100% sure...

**Comment by joelostblom** [comment]
Hi @John-BME and @pantufa, I can't say whether you have the correct answer to the assignment question, but it seems to me that your code does what is asked for in the question. Is there any specific reason you have for doubting that this plot would be correct?

**Comment by stefanmladjenovic** [comment]
Hi,
I hope you're doing well. Quick question: do you know why my graph looks different than the one presented here? 

I believe we are using the same data (as seen below):
```python 
# load in data
url = 'https://raw.githubusercontent.com/BME1478H/Winter2020class/master/data/world-data-gapminder.csv'
world_data = pd.read_csv(url)

# subset 2014 for this assignment
world_data_2014 = world_data.loc[world_data['year'] == 2014]
```
Our code is identical:
```python 
sns.lmplot('child_mortality', 'life_expectancy', hue='income_group',  data=world_data_2014)
```
However, our final graphs look different. I noticed that the scale on the x and y axis are different. There are other differences, namely that the graph I produced doesn't have as long of a regression line for the 'High' income_group (red line colour).
![a10_q2png](https://user-images.githubusercontent.com/71162611/99898943-92c24b00-2c73-11eb-9209-ec5217076542.png)

Please let me know when you have a chance if you have any thoughts on why these differences may appear. Also please let me know if you have any suggestions in the case that I prepared my answer incorrectly. 

Thank you,
Stefan
