### ISSUE TITLE
A11 - Clarification for Question 4 (pres vs Y_pred)

### ISSUE THREAD

**Issue by Shiroifuyuki** [BME1478H/Winter2020class#266]
Here is my code:
```python
#pres=tree_model.predict(X_test)
Y_pred=tree_model.predict(X_test)
# keep this code here
print(Y_pred.shape)
#print(pres.shape)
 ```
The question requests storage in Y_pred but the original code looks like the following :
 ```python
pres=
print(Y_pred.shape)
```
What is pres there for?

**Comment by joelostblom** [comment]
Hmm, I don't think `pres=` is in the notebook. I just downloaded it from quercus and this is what that cell looks like for me.

![image](https://user-images.githubusercontent.com/4560057/78851738-6d781980-79cf-11ea-862a-096007d9d988.png)

**Comment by Shiroifuyuki** [comment]
Interesting... I guess I downloaded it too early or something
