### ISSUE TITLE
PDF of Lecture Notes on Quercus

### ISSUE THREAD

**Issue by sadiloai** [BME1478H/Winter2020class#3]
Hello

I was wondering if it would be possible to post a pdf version of the lecture slides for taking notes as well as would you be able to post the solution to the examples that we attempt during the online lecture so that we can compare with our own code and troubleshoot.

Thank you

**Comment by profgarton** [comment]
Slides for week one and been uploaded to Quercus. Subsequent lectures will post solutions.
