### ISSUE TITLE
A2Q1 File with same names are overwritten

### ISSUE THREAD

**Issue by Brendannigel** [BME1478H/Winter2020class#30]

**Comment by RayNele** [comment]
Delete the template text, paste the code you tried between two backticks ` with a short explanation and I'll be there to help you shortly.

**Comment by Brendannigel** [comment]
Hello, I have been able to copy the files from the first subject into the a new files I named Analysis. However when I move onto the other subjects they have similar file names for different subjects such as data01 data02 etc. I have tried using --parents or --preserve=All and this does not seem to work. My Analysis file overwrites the new files I try to copy in. 

Code tried 'cp --parents *.eeg *.ext ../Analysis' and 'cp *.eeg *.ext ../Analysis --preserve=all'

**Comment by RayNele** [comment]
So you're actually supposed to copy of the folder and all its contents (including other folders) so that what you are left with is a mirror copy of the original directory, minus any jpg files

**Comment by Brendannigel** [comment]
so what I have been doing is going through each subject individually and essentially using this code 
' Owner@BrendanSamarooSurfacePro MINGW64 ~/desktop/assignment-data/20180204-01
$ cp *.eeg *.csv *.txt ../Analysis' 

which copies everything but the jpg files. Are you saying I should copy all the folders and maybe do a rm command to remove all the jpg files from the Analysis directory?

**Comment by RayNele** [comment]
Yes, a `cp` followed by a `rm` is perfectly fine


For the record, your code isn't working because you didn't copy the original directories with the dates onto it. So you're copying 1.eeg from the second folder into Analysis, which already has a 1.eeg from the first folder. 

You need to cp them into different folders, keeping the original structure.

**Comment by Brendannigel** [comment]
Sorry I am not sure what you by I am not copying the original directories with the dates onto it? Do you mean in the code I have to have to date somewhere in order for them not to be overwritten? 

So essentially can I create within the Analysis directory separate related folders for each subject and just copy the correct data and notes into each one?

**Comment by RayNele** [comment]
Sorry for the confusion. I mean that each .eeg is contained in a folder,
whose name is a date.

You are copying the file, but not the directory it is contained in.
Therefore after copying the first set of files, the second set will
overwrite them.

Ie: after the first loop, you have a full set of .eeg files in the Analysis
folder. When you copy over the next set, they have the same name, so you
overwrite them.

Instead you want to copy the .eeg files, AND the folder that contains them,
to keep the different .eeg files seperate.

You should end up with the exact same data structure as the original
downloaded assignment-data folder. Except for the fact that it has no jpg.
