### ISSUE TITLE
A2Q3 Rename Command Does Not Exist

### ISSUE THREAD

**Issue by waqassajid** [BME1478H/Winter2020class#32]
Hi I've done a ton of research into the most efficient way to rename files in Bash, and so far I have found that the "rename" command is the most effective tool to rename multiple files in multiple subdirectories. However, the rename command does not exist on my system. I've tried downloading and installing many different things to get the rename command on my system, but it continues to say "rename command does not exist" when I type in "rename" into the cmd interface. What am I doing wrong? I've attached a screenshot below. Thank you.

![rename command does not exist](https://user-images.githubusercontent.com/59673878/72687216-b2279f00-3ac9-11ea-8998-7d4c2640b829.jpg)

**Comment by RayNele** [comment]
You're not doing anything wrong. Rename is not a command that is installed
by default in git bash.

Unfortunately, git bash does not have an inherent package manager to
install packages with, so rename will not be a viable option for this
assignment.
