### ISSUE TITLE
General: Is it possible that we could have all the lectures and assignments to work ahead?

### ISSUE THREAD

**Issue by Shiroifuyuki** [BME1478H/Winter2020class#33]
Same request as title: Is it possible that we could have all the lectures and assignments posted in Quercus so we can work ahead/at our own pace (I am not suggesting we change submission dates, just availability of material ahead of time)?

**Comment by linamnt** [comment]
Hi @Shiroifuyuki. Unfortunately, that is not possible as a lot of material is still being refined for the course in an ongoing manner. I understand the need for working at your own pace, but we are trying to make assignments straightforward and less time-consuming going forward, and hopefully that can help with reducing the weekly load on students.
