### ISSUE TITLE
A2Q4 how to determine the path to the external hard drive

### ISSUE THREAD

**Issue by ilenehe** [BME1478H/Winter2020class#34]
I # the diff command to avoid any error, because I am not too sure where the contents in the external hard drive will be mounted. Anyone has any ideas?
I've tried 
find / -type d -name 'assignment-data'
not too sure if it will work, at least not on my pc.

**Comment by joelostblom** [comment]
There is no external hard drive, you are just writing a file that would check all the folders from the original location and the location you copied them to (which in the wording of the question is an external hard drive, but for you is where you copied the files to in q1).

**Comment by ilenehe** [comment]
@joelostblom Thank you so much for clarifying. It does help!
