### ISSUE TITLE
L3 Challenge Q1: NameError: name 'str1' is not defined

### ISSUE THREAD

**Issue by brennen-uoft** [BME1478H/Winter2020class#39]
I'm trying to do the last challenge (q1) in our week 3 lesson and I don't know why I'm getting the error below?

sen1 = ('The pale Blue dot')

def sentence_analytics(s):
    d = {'upper_case':0, 'number_of_spaces':0}
    for c in s:
        if c.isupper():
            d['upper_case']+=1
        elif c.isspace():
            d['number_of_spaces']+=1
        else:
            pass
    print('No. of upper case characters', ' = ', d['upper_case'])
    print('No. of spaces', ' = ', d['number_of_spaces'])
    return str1.split()

word_list = sentence_analytics(sen1)

word_list

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-22-935284634f67> in <module>
     12     return str1.split()
     13 
---> 14 word_list = sentence_analytics(sen1)
     15 word_list

<ipython-input-22-935284634f67> in sentence_analytics(s)
     10     print('No. of upper case characters', ' = ', d['upper_case'])
     11     print('No. of spaces', ' = ', d['number_of_spaces'])
---> 12     return str1.split()
     13 
     14 word_list = sentence_analytics(sen1)

NameError: name 'str1' is not defined

**Comment by RayNele** [comment]
>name 'str1' is not defined

It seems you haven't defined any variable named `str1`

**Comment by brennen-uoft** [comment]
This is what was provided in the lesson and it doesn't appear that str1 is ever defined either?

![Screen Shot 2020-01-22 at 4 16 34 PM](https://user-images.githubusercontent.com/59633043/72935108-b73b5700-3d32-11ea-851c-fdb88d6107d8.png)

**Comment by RayNele** [comment]
ah that's a typo on our part sorry about that. 

it should be `s.split()`

**Comment by brennen-uoft** [comment]
That fixed it. Thanks.
