### ISSUE TITLE
Assignment 2 question 2

### ISSUE THREAD

**Issue by moonj94** [BME1478H/Winter2020class#4]
I'm trying to execute this code and I get the following output.

I want to be able to output the directories that do not contain a file which contains the string, 'notes'. I think I may have to use grep but I'm not sure how to go about doing this.

I'm supposed to get one folder as the output as this folder does not contain a note file.

![image](https://user-images.githubusercontent.com/53019885/72459885-62776980-3791-11ea-94f5-36dccb9c0ef0.png)

I have also tried:

![image](https://user-images.githubusercontent.com/53019885/72460109-cd28a500-3791-11ea-83f0-35cd64222783.png)

**Comment by RayNele** [comment]
Hey Jaewoong,

I wasn't able to get that solution from stackoverflow to work either.

I would read into the man pages for these commands before you blindly copy
paste them in without knowing what each argument does.

The solution I came up with uses the bash commands `find`, and `comm`, but
you're free to try any other solution, including loops, as long as it
produces the desired output.

**Comment by moonj94** [comment]
It's okay I didn't use find or comm, just a  combination of ls and grep to produce a boolean output from which I  parsed the directories with no note file or info.csv.  Problem solved
