### ISSUE TITLE
A3Q2b - code only outputting 1 number? - please help

### ISSUE THREAD

**Issue by rennmela** [BME1478H/Winter2020class#43]
def squared_error(a,b):

     residual = b - a #the difference between our prediction and data

     mse = sum(residual**2)/len(b) #use the residual to calculate the mean squared error

     return mse #return the result
**input:**
mse = [] #initialize a list to store our results
i = 0
for i in range(len(range_rate)):
 prediction = N0 * np.exp(range_rate[i]*t)
 error = squared_error(prediction,population_size_noise)
 i = i + 1
mse.append(error)
print(mse)
 #find the index of the minimum value in mse
idx_min_mse = min(mse)
print(idx_min_mse)

**output:**
[286658756767.105]
286658756767.105

**Comment by RayNele** [comment]
>#find the index of the minimum value in mse

the function `min` finds the minimum value in the mse array. which is a single value since it's the lowEST value. Seems like it's working as intended.

**Comment by rennmela** [comment]
shouldn't mse be an array?

**Comment by RayNele** [comment]
@rennmela 

yep mse is an array.

if you `print(mse)` you should see all its values.

however you've printed `idx_min_mse` you should see the lowest value in `mse`

**Comment by rennmela** [comment]
I am printing mse and idx_min_mse.

**Comment by RayNele** [comment]
@rennmela  ah sorry, my mistake I missed that.

anyways I copied your code word for word and it works, I can't tell since you didn't use backticks to format your code in this post, but I would guess that you haven't indented the mse.append(error) line?

**Comment by rennmela** [comment]
sorry for not formatting properly (aka newbie). I did indent though in my code, but it seems like its only looking the one time. Not sure why.

**Comment by RayNele** [comment]
can I see your range_rate variable? my second guess would be that it has a length of 1

**Comment by rennmela** [comment]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

**Comment by RayNele** [comment]
what happens when you try this `squared_error(population_size,population_size_noise)`

**Comment by rennmela** [comment]
![Screen Shot 2020-01-22 at 11 32 50 PM](https://user-images.githubusercontent.com/59658418/72956890-83325700-3d6f-11ea-97c0-952c4f9b1724.png)

**Comment by RayNele** [comment]
instead of `np.nditer` which I honestly have never used before but looks to be a multidimensional iterator (we're only working with a 1-dimensional array), change that back to what you've copied to me before.

**Comment by RayNele** [comment]
>for i in range(len(range_rate)):

what you had here actually is the most "pythonic" way to do it, so that was "correct" for the most part.

**Comment by rennmela** [comment]
![Screen Shot 2020-01-22 at 11 43 11 PM](https://user-images.githubusercontent.com/59658418/72957269-f6889880-3d70-11ea-8990-06e1fcfc3ef1.png)

**Comment by RayNele** [comment]
seems like it's working. 


your `best_fit` doesn't work since your `idx_min_mse` doesn't follow what the instructions said to do.

instead of 
>find the index of the minimum value in mse

you found the actual value.

when you reference the index later in the mse array, it does return the same value as `min(mse)` but unfortunately that's not what the instructions ask you to do.

**Comment by rennmela** [comment]
ok, thank you.
