### ISSUE TITLE
A3Q2 - code output overflow. Please help

### ISSUE THREAD

**Issue by rennmeli** [BME1478H/Winter2020class#44]
![Screen Shot 2020-01-22 at 11 35 02 PM](https://user-images.githubusercontent.com/59658814/72957005-e91ede80-3d6f-11ea-8e05-d85a8157abae.png)

Code output overflow.

**Comment by RayNele** [comment]
@rennmeli 

if idx_min_mse is the index (the position in the array) of the smallest value in mse, then best_fit should be using that index to look up which growth rate that index corresponds with in range_rate
