### ISSUE TITLE
Comments for assignment 3

### ISSUE THREAD

**Issue by t-christ1** [BME1478H/Winter2020class#46]
For questions 2b and 3 where most of the lines are provided, is it acceptable to copy and paste these functions and then leave the comments that are already provided for them? Or would you like us to form original comments on these commands?

**Comment by joelostblom** [comment]
You are allowed to use all the code and comments given to you in the assignment. In general, You can add your own comments if you consider that some sections are not explained sufficiently well or if you are adding code that needs explaining.
