### ISSUE TITLE
Question 2, assignment 3 - iteration 

### ISSUE THREAD

**Issue by fakharin** [BME1478H/Winter2020class#47]

**Comment by fakharin** [comment]
Hey guys, 
is it possible for you guys to help me with this error?
<img width="782" alt="Screen Shot 2020-01-24 at 4 42 29 PM" src="https://user-images.githubusercontent.com/59659481/73106148-b50b0100-3ec8-11ea-8b84-3d96e69d0f35.png">

**Comment by RayNele** [comment]
When k is the last digit in the length of `population_noise_size_array` you're trying to index one past that, which doesnt work. 

ie: if the array has a length of 4, and you're on the last iteration of the loop, k=4, you can't index the array at k+1=5 since it doesnt exist.

**Comment by fakharin** [comment]
Do we have to write a code for it In order to iterate?

**Comment by RayNele** [comment]
@fakharin not sure what you mean there, but you cant index a variable past its available size. 

If you have a cupboard with 4 drawers, you can look in the 0th, 1st, 2nd or 3rd drawers, but if I ask you to look in the 4th, that's not possible.

**Comment by RayNele** [comment]
@fakharin as for the indented block, it looks indented to me, maybe try running the cell again.

**Comment by joelostblom** [comment]
@fakharin If you're still receiving the indentation error, please paste your code as text instead of as an image and we can try to run it to see what is wrong. If your problem has been resolved, please close this issue.
