### ISSUE TITLE
A copy of the code as a .py file

### ISSUE THREAD

**Issue by rennmela** [BME1478H/Winter2020class#48]
Using Jupyter Lab, under File > Export Notebook as > Choose "Executable Script", it downloads a .py.html file. Is that ok to submit?

**Comment by joelostblom** [comment]
It should download as a `.py` file, not sure why it would also have an `.html` extension. Make sure you select to save it and don't open it in the browser first and then save it.

**Comment by t-christ1** [comment]
Mine is doing the same thing, I worked on the whole assignment in Jupyter Notebook (in a browser), when I open the .ipynb file it opens in atom (it also says .ipynb.json? not sure if that matters?)

**Comment by joelostblom** [comment]
`.ipynb` files are in json format, and will open in the system default program if they are double clicked from a file browser. They can only be opened as Jupyter Notebooks from within JupyterLab.

For `.py.html`, try opening that file in a text editor (such as notepad or textedit), does it look like a python file or like an html file?

Another way of exporting is to run `jupyter-nbconvert` from terminal. Any terminal command can also be run inside the jupyter-notebook if you prepend an `!`, so you could type this in a cell and execute it: `!jupyter-nbconvert your-notebook.ipynb --to python`.

**Comment by linamnt** [comment]
I've confirmed with a student in class that the .py.html reads fine in a text-editor. I think it just makes it possible to open in a browser for some reason. 
The files should work fine. If you're having troubles submitting on Quercus, please try again, I just removed the restriction on file extensions.
