### ISSUE TITLE
Quercus says "file type not allowed"

### ISSUE THREAD

**Issue by t-christ1** [BME1478H/Winter2020class#49]
When I try to add my .ipynb file quercus tells me "This file type is not allowed. Accepted file types are: py and ipynb" even though my file is .ipynb. It won't let me submit.

**Comment by joelostblom** [comment]
We have received submissions quercus with ipynb and py files, so the files you are trying to upload are likely in the incorrect format. Confirm that you are not hiding file extensions in your operating system and that there are not double file extensions, e.g. `.ipynb.json`. Open the files in a text editor and check that they look like either a [py-file](https://raw.githubusercontent.com/mwouts/jupytext/master/demo/Benchmarking%20Jupytext.py) or a [ipynb-file](https://raw.githubusercontent.com/mwouts/jupytext/master/demo/World%20population.ipynb).

**Comment by t-christ1** [comment]
Both files open fine in text editor but how would I know if they look like a specific file? I think the ipynb saved as a .json how do I change the format? I did my whole assignment in jupyter notebook but in a browser, I dont understand how to run it without going through the browser? Whenever I click launch in anaconda it automatically opens it in a browser and when I try to do commands in the terminal nothing happens (i tried the command jupyter-nbconvert assignment3.ipynb --to python already)

**Comment by joelostblom** [comment]
*Feel free to submit your assignment files via email if this is not working for you.*

---

> Both files open fine in text editor but how would I know if they look like a specific file?

The links I posted in my previous comment gives you an idea of what the file types should look like.

> I think the ipynb saved as a .json how do I change the format? 

Notebooks are technically json-files with a different file-ending: `ipynb`.

> I did my whole assignment in jupyter notebook but in a browser, I dont understand how to run it without going through the browser? Whenever I click launch in anaconda it automatically opens it in a browser and when I try to do commands in the terminal nothing happens 

This sounds fine, JupyterLab should open in the browser, this will not impact your file types.

> when I try to do commands in the terminal nothing happens (i tried the command jupyter-nbconvert assignment3.ipynb --to python already)

The easiest might be to put that line in a notebook cell with an `!` prepended. If you use the terminal you will need to use the anaconda prompt and navigate to the same dir as your notebook.

**Comment by linamnt** [comment]
Hi @t-christ1 I think @joelostblom gave a good explanation of why it might have those things appended to the filename. 

I removed the restriction from quercus, but we do still expect the two files should be readable as Jupyter Notebooks, and Python scripts (this just removes the restriction in case of the problems with the output filenaming conventions.).
