### ISSUE TITLE
Man command not working

### ISSUE THREAD

**Issue by dtovbis** [BME1478H/Winter2020class#5]
Following along with the lecture slides. When I try to use "man" in git Bash, I get a "command not found" error.

**Comment by RayNele** [comment]
Unfortunately some versions of git bash do not support man. Try command
--help instead.

Ryan.

**Comment by dtovbis** [comment]
cal is not available either, is this the same issue?

**Comment by RayNele** [comment]
Yeah most of the "system" commands only apply to actual unix/linux
machines.

**Comment by joelostblom** [comment]
The `info` command might also exist. You should be able to see the available commands by [listing the contents of the bin directory](https://stackoverflow.com/a/27873584):

```bash
cd /bin
ls -1
```

If that works, please post it here for reference if you don't mind. I am not on Win myself so can't check.

**Comment by dtovbis** [comment]
info does not exist, but the /bin ls-1 works.
