### ISSUE TITLE
A3Q2 question about squared_error parameters

### ISSUE THREAD

**Issue by stefandenkovski** [BME1478H/Winter2020class#51]
Hello, 

The instructions for Q2 and thus Q3 are slightly confusing. 
Do you want Q2 to us to hard code that the data observed is always = population_size_noise? 
Or do you just want us to pass population_size_noise in as data in Q3 to the function we write in Q2?

**Comment by RayNele** [comment]
No, you do not hard code that data observed is always = population_size_noise. 

you are to create a function, `squared_error`, which takes 2 parameters, prediction and data, and returns mse. Everytime you call on `squared_error`, it should look like this:

`squared_error(parameter1, parameter2)`, whether or not the observed data is always = population_size_noise is irrelevant to the creation of this function. 

you then later, call on this squared_error funciton within the for loop where the second parameter would indeed be hardcoded as `population_size_noise. `

feel free to ask for more clarification if this was still confusing.
