### ISSUE TITLE
Grade for A2 is not visible.

### ISSUE THREAD

**Issue by faezahari** [BME1478H/Winter2020class#523]
Hi TAs,

I received an email stated that the grade for my Assignment 2 has been posted. But, the mark is not visible on Quercus.

**Comment by RayNele** [comment]
Hi, for questions regarding visibility of marks, late submisisons, or general quercus issues, send your marking TA an email which we will then either try to fix on quercus, or forward to Prof Garton if the issue can't be fixed.
