### ISSUE TITLE
Week 4 and 5 lecture information?

### ISSUE THREAD

**Issue by moonj94** [BME1478H/Winter2020class#53]
I see in the files tab there is a folder for week 4 and 5 but the lecture and notes/slides are not there yet.

**Comment by moonj94** [comment]
1) are we skipping week 4?
2) are there no lecture slides or videos?

**Comment by joelostblom** [comment]
There was an announcement on quercus on Jan 24th ("Course concerns and feedback") stating that there will be no new material for week four. I can see that you are registered on quercus so you should have received this message. If you are not receiving the announcements for some reason, please send us an email (or email quercus support directly if you think it is an issue with the platform).
