### ISSUE TITLE
1b assignment 4 delimiter ','

### ISSUE THREAD

**Issue by rennmela** [BME1478H/Winter2020class#56]
It doesn't seem to be adding the delimiter ',' :

![Screen Shot 2020-02-07 at 8 40 53 AM](https://user-images.githubusercontent.com/59658418/74034123-a4a55c80-4985-11ea-9bdc-e427bdb7bcf0.png)

**Comment by RayNele** [comment]
Delimiter specifies that you're READING the comma as a delimiter from the file and not adding it as a delimiter to your array.
