### ISSUE TITLE
Assignment 4 'detect_problems' function

### ISSUE THREAD

**Issue by rennmela** [BME1478H/Winter2020class#57]
I was trying to check to see if it was working:
![Screen Shot 2020-02-07 at 9 08 32 AM](https://user-images.githubusercontent.com/59658418/74036041-817cac00-4989-11ea-8333-44b38dce1b62.png)

**Comment by RayNele** [comment]
You can't call on a function without its parameters. 

You did `checkzeros(patient_summary)` which is fine, but unless you store that in a variable, it's a redundant line of code that you can't access. 

`x=checkzeros(patient_summary)`

`return x`

**Comment by RayNele** [comment]
#58
