### ISSUE TITLE
Question 2a Assignment 4

### ISSUE THREAD

**Issue by rennmela** [BME1478H/Winter2020class#58]
I started writing the code, but I'm not exactly sure what the inputs are. Can you please clarify?

![Screen Shot 2020-02-07 at 9 08 32 AM](https://user-images.githubusercontent.com/59658418/74062944-6592fd80-49bd-11ea-96ec-4350f8871d20.png)

**Comment by RayNele** [comment]
Same issue as before, but basically, theres a function `check_zeros`. It checks for zeros within an array.

This doesn't have a value unless you have that input array. You're asking your `detect_problems` function to return something that has no value, so it's telling you that it's a function. 

If you instead assign `check_zeros(patient_summary)` to a variable and return that variable, it'll work. (Just like I said in the last answer)


Heres a more concrete example. 

Lets say your function is `f(x)` where `y = 3x + 2`. 

It would look like this:
