### ISSUE TITLE
Question 2 Assignment 4

### ISSUE THREAD

**Issue by rennmela** [BME1478H/Winter2020class#59]
Sorry, I posted the wrong screenshot before. I started writing this code, but I'm not sure what the inputs are.

![Screen Shot 2020-02-07 at 3 35 28 PM](https://user-images.githubusercontent.com/59658418/74063916-7c3a5400-49bf-11ea-9da3-e485dc8e592f.png)

**Comment by joelostblom** [comment]
If this is a comment on #58, could you please post it there instead of opening a new issue? Or clarify if this is a new question and how it's different from 58.

**Comment by rennmela** [comment]
It's a separate issue. I posted the wrong screenshot.

**Comment by joelostblom** [comment]
Ok could you add more details about the problem? Are  you on a, b, or c? What have you tried that didn't work?

**Comment by rennmela** [comment]
I'm working on 2b and c.I'm not understanding what we have as inputs to each function.

**Comment by joelostblom** [comment]
For b, the method should be able to read a csv file so you need an input argument that says where this csv is located. 

For c, the method parameters are already stated in the question, but maybe I'm misunderstanding what you're asking?
