### ISSUE TITLE
Incorrect files being returned?

### ISSUE THREAD

**Issue by aabouzid** [BME1478H/Winter2020class#60]
Hi,

I'm not getting the 3 files that should be found in assignment 4, question 2d. My "Experiment" class looks like this:

    def patient_summary(self, operation):
        ax = 0
        if operation == 'mean':
            summary_values = (self.data).mean(axis=ax)
        elif operation == 'max':
            summary_values = (self.data).max(axis=1)
        elif operation == 'min':
            summary_values = (self.data).min(axis=1)
        return summary_values

The output I get is a list of all 12 files rather than the 3 files that should be flagged. However, if I use 'max' rather than 'mean' or 'min' in the loop, the output is 3 files that are flagged (files 3, 8, and 11), and I'm not sure why this is the case. Any help would be appreciated!

Thank you in advance

**Comment by RayNele** [comment]
I'm away from a computer right now to test so I might be mistaken but I believe you want the mean across the row, so axis = 1

**Comment by aabouzid** [comment]
Thank you! That fixed the problem.
