### ISSUE TITLE
Can't open Assignment 4 

### ISSUE THREAD

**Issue by t-christ1** [BME1478H/Winter2020class#61]
When I download the 'last_first_assignment4.ipynb' file and try to open it on my mac it says there is no application to open the document? I've tried clicking 'open with' but it doesn't give me any options except adobe PDF reader and TextEdit to open (these don't work). 

Help

**Comment by t-christ1** [comment]
For anyone wondering, I figured it out - went to Jupyter lab and clicked open from path and then typed the path to the file on my computer!

**Comment by joelostblom** [comment]
Thanks for including your solution after closing!
