### ISSUE TITLE
Task2,e

### ISSUE THREAD

**Issue by FarnazKhodami** [BME1478H/Winter2020class#623]
Hello,

I have a question about the final plot of Task2, part e. I can't get what should be on the X-axis. There are many parameters. I have used 'id' on the X-axis:
![Task2e](https://user-images.githubusercontent.com/109175909/200191819-7fae3172-caca-4fd7-991a-f7dbbc55bff2.png)

but I don't know where should I use 'time'. Should I use 'time' on the X-axis instead of 'id'?

Thanks for your time.

**Comment by cancer-ray** [comment]
> e. Plot a boxplot() specifically of the pulse of the no fat and low fat diet groups for each time point in the running group. Start by subsetting the data into a new variable.

it would be correct here to use time in the x axis instead of ID

**Comment by FarnazKhodami** [comment]
Thanks so much for your response.
