### ISSUE TITLE
Assignment 2, Question 3 Clarification

### ISSUE THREAD

**Issue by MDHermans** [BME1478H/Winter2020class#626]
Question asks to "write a loop that renames all of the note text files in each folder to: notes.txt". Does this include the copied note files in DATA_ANALYSIS, or is it only referring to the subfolders under assignment-data?

**Comment by cancer-ray** [comment]
each of the questions should be stand-alone, and solutions should work on
the original assignment files (before you have modified or changed them).

**Comment by MDHermans** [comment]
Oh I see, thanks for clarifying Ryan, that's very helpful!
