### ISSUE TITLE
A2Q4 - including a path for the hard drive 

### ISSUE THREAD

**Issue by nayana31** [BME1478H/Winter2020class#627]
For Assignment 2, question 4, I'm unsure as to whether we are actually supposed to be able to run our code or if it's supposed to act as an example and can have filler text for the hard drive like /path/to/drive.

I've looked at previous answers about this question and I think the question has changed since 2020 because I believe we're supposed to compare folders that exist in the hard drive to the original data downloaded from Quercus, not the data in Q1 since we were only supposed to copy files for that question, not the folders themselves. For this question, is it ok to include a filler text line for the hard drive location before writing the code for the comparison since I don't actually have a hard drive to use?

**Comment by cancer-ray** [comment]
yeah, it's more if a hypothetical question, but if you want to test it, you
can always make a copy of the assignment-data folder and delete a few
files.

**Comment by nayana31** [comment]
thank you!
