### ISSUE TITLE
A4 Q2d. "Type Error: Experiement.add_data() takes 1 positional argument but 2 were given"

### ISSUE THREAD

**Issue by araujoor** [BME1478H/Winter2020class#634]
Hello! I am having an issue with Question 2d. I have looked through github and haven't found anyone with a similar issue. I'm not sure what the error message is trying to tell me. "Type Error: Experiement.add_data() takes 1 positional argument but 2 were given"
![Screen Shot 2023-10-08 at 11 54 48 AM](https://github.com/BME1478H/Fall2022class/assets/144946669/c67995c4-1898-4ffa-b10a-5ca7f7ede9de)
![Screen Shot 2023-10-08 at 11 55 06 AM](https://github.com/BME1478H/Fall2022class/assets/144946669/72d38c62-7295-48a8-96d1-bc1b86c208d6)

**Comment by cancer-ray** [comment]
looks mostly correct. The loop doesnt need to be part of where you define
the class.

I would also guess where you are assigning values to fnames is incorrect,
but I cant see in these screenshots.

**Comment by cancer-ray** [comment]
for reference, the error message is telling you that you are giving too
many arguments. For example, if you write a function that adds two numbers,
you are calling the function with 3 numbers so it doesnt know what to do
with the third number.

**Comment by araujoor** [comment]
Hi Ryan,

Thank you for your response!

I figured out that there was an error with the indentation! It works now.

Best,
Oriana
________________________________
