### ISSUE TITLE
Assignment 4- Q2- Last part - Error

### ISSUE THREAD

**Issue by AvaDanialy** [BME1478H/Winter2020class#65]
I tried to move around the given code as shown below but faced this error and don't know why.
"add_data() takes 1 positional argument but 2 were given"
Here's how I defined "add_data()"
<img width="831" alt="Screen Shot 2020-02-12 at 12 44 33" src="https://user-images.githubusercontent.com/59749820/74361881-a7dd8580-4d95-11ea-97ac-02d53ad0ae62.png">

Here's the last part of Q2:
<img width="1067" alt="Screen Shot 2020-02-12 at 12 44 21" src="https://user-images.githubusercontent.com/59749820/74361929-baf05580-4d95-11ea-8d16-906b4c5b936f.png">

Could you tell me what's wrong?

**Comment by RayNele** [comment]
Can I dee how you've defines fnames?

**Comment by RayNele** [comment]
Also, you must pass `self` through your class method unless it is a static method. 

That's most likely the problem here.
