### ISSUE TITLE
A42b&d - How to read a csv and "class takes no arguments"-error

### ISSUE THREAD

**Issue by rennmela** [BME1478H/Winter2020class#66]
![Screen Shot 2020-02-12 at 1 24 19 PM](https://user-images.githubusercontent.com/59658418/74364899-09ecb980-4d9b-11ea-90b3-8c0c358c0780.png)

**Comment by joelostblom** [comment]
Happy to help. In order to be able to do so effectively, please first read through the issue template and provide us with details of which part of the question you are struggling with, what you have tried, and what did not go as expected including any errors you encountered..

**Comment by rennmela** [comment]
I don't quite understand how to code question b.  the def add_data. I coded what's above, but I don't think it's right.

**Comment by joelostblom** [comment]
Have you tried to read a csv file using that code? What happens when you try to execute it? I would recommend creating a simple CSV file yourself and use it for testing.

**Comment by rennmela** [comment]
ok so I fixed a,b,c and it seems to be working, but now there's an error in d.
![Screen Shot 2020-02-13 at 11 07 22 AM](https://user-images.githubusercontent.com/59658418/74453870-0451ab00-4e51-11ea-9e6e-a6cdf66bdf2a.png)
![Screen Shot 2020-02-13 at 11 07 35 AM](https://user-images.githubusercontent.com/59658418/74453894-0b78b900-4e51-11ea-9417-186eaf426974.png)

**Comment by joelostblom** [comment]
A hint to what is going on here is to look at the indentation of your code. You want to the callables that you have defined to be class methods, but they are currently defined at top level, so your class has no `__init__` method.

For the future, could you post your code as text in a markdown code block instead of as a screenshot? It is faster for us to troubleshoot if we can copy paste to try your code easily instead of just looking at the screenshot. Likewise, providing a detailed description of the problem and a descriptive title enables us to hep faster. I updated your title as an example.

**Comment by rennmela** [comment]
Sorry, I still don't understand. What do you mean by my class has no _init_method? Here's my code:
# TODO: modify this basic class as per the instructions above
class Experiment:
    study = 'arthritis'
    experimenter ='Dr. Aria'
def __init__(self,session_no):
    self.session_no = session_no
    self.data = None
def add_data(self,fnames):
    self.data = np.loadtxt(fnames, delimiter = ',')
def patient_summary(self, operation):
    # TODO: specify the axis, 0 or 1
    ax = 1
    # TODO: fill in the rest of the if(and or elif/else) statements
    if operation == 'mean':
        summary_values = self.mean(axis=ax)
    elif operation == 'max':
        summary_values = self.max(axis=ax)
    else:    
        summary_values = self.min(axis=ax)
    return summary_values

**Comment by rennmela** [comment]
Sorry, I still don't understand. What do you mean by my class has no _init_method? Here's my code:
# TODO: modify this basic class as per the instructions above
class Experiment:
    study = 'arthritis'
    experimenter ='Dr. Aria'
def __init__(self,session_no):
    self.session_no = session_no
    self.data = None
def add_data(self,fnames):
    self.data = np.loadtxt(fnames, delimiter = ',')
def patient_summary(self, operation):
    # TODO: specify the axis, 0 or 1
    ax = 1
    # TODO: fill in the rest of the if(and or elif/else) statements
    if operation == 'mean':
        summary_values = self.mean(axis=ax)
    elif operation == 'max':
        summary_values = self.max(axis=ax)
    else:    
        summary_values = self.min(axis=ax)
    return summary_values

**Comment by joelostblom** [comment]
I can't troubleshoot that code since it does not have any indentation, please format your code as text in a markdown code block (using tripple backticks as indicated in the [issue template](https://github.com/BME1478H/Winter2020class/blob/master/.github/ISSUE_TEMPLATE/question-template.md)).

You can use tab completion or `dir(Experiment)` to view all the defined class attributes.

**Comment by rennmela** [comment]
```
# TODO: modify this basic class as per the instructions above
class Experiment:
    study = 'arthritis'
    experimenter ='Dr. Aria'
def __init__(self,session_no):
    self.session_no = session_no
    self.data = None
def add_data(self,fnames):
    self.data = np.loadtxt(fnames, delimiter = ',')
def patient_summary(self, operation):
    # TODO: specify the axis, 0 or 1
    ax = 1
    # TODO: fill in the rest of the if(and or elif/else) statements
    if operation == 'mean':
        summary_values = self.mean(axis=ax)
    elif operation == 'max':
        summary_values = self.max(axis=ax)
    else:    
        summary_values = self.min(axis=ax)
    return summary_values    
```

**Comment by rennmela** [comment]
Does that work?

**Comment by joelostblom** [comment]
Yes, that looks good, thanks for updating. I appended `python` to the opening tripple backtick so that GitHub uses syntax highlighting for the code (as you can see above).

If you do `dir(Experiment)`, you will see that none of `add_data` or `patient_summary` is defined for the Experiment class (`__init__` is , but with an automatic construction, not yours). The reason for this is that you have not indented your definitions properly so they are not part of the class. Study the example code in the assignment ans you can see what the proper indentation looks like.

**Comment by rennmela** [comment]
ok I fixed the indentation.
```
class Experiment:
    study = 'arthritis'
    experimenter ='Dr. Aria'
    def __init__(self,session_no):
        self.session_no = session_no
        self.data = None
    def add_data(self,fnames):
        self.data = np.loadtxt(fnames, delimiter = ',')
    def patient_summary(self, operation):
        # TODO: specify the axis, 0 or 1
        ax = 1
        # TODO: fill in the rest of the if(and or elif/else) statements
        if operation == 'mean':
            summary_values = self.mean(axis=ax)
        elif operation == 'max':
            summary_values = self.max(axis=ax)
        else:    
            summary_values = self.min(axis=ax)
        return summary_values        
```

**Comment by joelostblom** [comment]
Good, is it working for you now? If so could you close this issue? If not, could you post details about the new error?

**Comment by rennmela** [comment]
So I"m getting the following error now. Not sure what to do. 
![Screen Shot 2020-02-15 at 12 18 33 PM](https://user-images.githubusercontent.com/59658418/74592233-4adc0c80-4fed-11ea-938c-57808f68833e.png)
```
class Experiment:
    study = 'arthritis'
    experimenter ='Dr. Aria'
    def __init__(self,session_no):
        self.session_no = session_no
        self.data = None
    def add_data(self,fnames):
        self.data = np.loadtxt(fnames, delimiter = ',')
    def patient_summary(self, operation):
        # TODO: specify the axis, 0 or 1
        ax = 1
        # TODO: fill in the rest of the if(and or elif/else) statements
        if operation == 'mean':
            summary_values = self.mean(axis=ax)
        elif operation == 'max':
            summary_values = self.max(axis=ax)
        else:    
            summary_values = self.min(axis=ax)
        return summary_values        
# TODO: move these lines around and indent as necessary to make it work again, it *should* find three files.
session_counter = 1 # initialize counter 
for f in fnames: # iterate over data files
    exp = Experiment(session_counter) # create an instance of our experiment and give it a session_no
    exp.add_data(f) # read in our data to our experiment
    values = exp.patient_summary("mean") # get our patient means
    if check_zeros(values): # check whether any 0s in our means
        print(f) # print filename
    session_counter += 1 # increment our counter to the next session number
```

**Comment by RayNele** [comment]
Your data is actually stored in `self.data`

**Comment by joelostblom** [comment]
What @RayNele said. More details in these two previous comments:

- https://github.com/BME1478H/Winter2020class/issues/68#issuecomment-585888219
- https://github.com/BME1478H/Winter2020class/issues/76#issuecomment-586440254

**Comment by joelostblom** [comment]
Assuming that this is resolved since the issue solution has been posted in the linked comments above, please reopen if not.

**Comment by rennmela** [comment]
Honestly no, it hasn't been resolved. I opened this issue 3 days ago and have made zero progress. This online forum has not been very helpful. I've resorted to asking a friend of mine who is a data scientist for help because this is ridiculous.

**Comment by joelostblom** [comment]
>  I opened this issue 3 days ago and have made zero progress.

@rennmela Sorry, but I do not understand. We have resolved three of your issues in this thread and linked you to solutions and issues for further discussion of your fourth problem. Why do you think this is zero progress?

> This online forum has not been very helpful. I've resorted to asking a friend of mine who is a data scientist for help because this is ridiculous.

As part of this course, you are learning to ask questions in a way that will be helpful when you need to ask for help in the future on sites such as StackOverflow and GitHub (this is why we have linked to their resources for how to write good questions). As you can read in the issue template, it is not sufficient to simply post a screenshot of your code and say "Help". If everyone did this, the TAs would have to spend much more time figuring out what is wrong and not have time to help everyone that needs it. So both for your own benefit and to show solidarity to your classmates, your are encouraged to describe your issue in sufficient detail that we can help without sitting next to you and having a conversation (which would be the ideal solution if there were enough resources).

We can't simply give you the solutions, then you would not learn anything and it would not be fair to others that come up with the solutions themselves. We are here to provide hints on how you can proceed and help with specific problems when you get stuck. This is what I have tried to do in this thread: asking for clarification, giving tips on how to troubleshoot your code, and answering specific questions. Through this process, you have resolved three of your issues (how to code b, no "mean" attribute, and tuple index out of range). You have now encountered a fourth issue, for which @RayNele gave you a hint and I linked to two other issues where this discussion is already happening. It is very inefficient to discuss the same problem in multiple issues, instead you are welcome to take part of the solutions in the comments I linked and further the discussion in those issues if things are still unclear to you.

**Comment by rennmela** [comment]
I'm not simply asking for the solutions, but maybe your focus should not be on renaming the thread but addressing the issue in the code. I've been working on this code for over a week now and had been stuck on the same question. I don't appreciate you saying that I'm asking for the solutions. I am not and maybe you would have noticed this if you cared to look at my code to help me troubleshoot the issues. I post screenshots of the issues and your immediate answer is to refer to the name of the thread. Sure, I will work on providing a more detailed description in the future, but perhaps your focus as a TA in this course should be to help with the assignments.

**Comment by joelostblom** [comment]
@rennmela Sorry, but I do not understand. We have resolved three of your issues in this thread and linked you to solutions and issues for further discussion of your fourth problem. Why do you think I have not looked at your code?

As you can see on the comments above, my first focus was clarification of your question and suggestions to troubleshoot, after that I renamed the issue. Properly names issues help your classmates find solutions to their problems. The focus of the TAs in this course is to help all students as effectively as possible, and for that we require more than a screenshot without a question or an error message. Again, this helps both the TAs, yourself, and your classmates.

The mention of solutions was to explain how the TA team works, not to suggest that you have asked for solutions. I am sorry if it came across that way and I have edited my comment to take out that part so it is clear to you what I meant.

Further comments can also be found in https://github.com/BME1478H/Winter2020class/issues/84 in case it is helpful to hear it explained in another way. If the online help is not sufficient for you, I'd recommend showing up to the in person TA sessions for extra help.

**Comment by rennmela** [comment]
I do agree. the online help has not been sufficient, but the alternative, 'the TA help sessions', have not been either. So I have resorted to looking for help elsewhere.
