### ISSUE TITLE
A4, Q1C - Giving an error message

### ISSUE THREAD

**Issue by chowd505** [BME1478H/Winter2020class#69]
![image](https://user-images.githubusercontent.com/59659816/74455714-c1450700-4e53-11ea-8de3-f2d4e4f2df47.png)

I am getting an error message for Q1C and I am not sure whether I missed any code or not?

Please help and correct me if possible.

**Comment by RayNele** [comment]
Extra equals sign there. 

== Is for comparisons. Single = is for assignment.

**Comment by chowd505** [comment]
Thanks
