### ISSUE TITLE
Assignment 2 Format

### ISSUE THREAD

**Issue by georgeamatyas** [BME1478H/Winter2020class#7]
Hello,

Are we submitting a bash script for this assignment? 

Also, how would you like us to do question 4? I compared the directories of the original data to the directories made in question 1. Is this correct?

**Comment by RayNele** [comment]
A labelled pdf document containing the text for the commands should be suitable for this week's submission. 

Ie:

1. `my-answer-in-code`

2. Etc.

No screenshots are necessary.

**Comment by moonj94** [comment]
Is it okay if we still make a pdf of screen shots of the code, output, and results?

**Comment by RayNele** [comment]
@moonj94  **The raw text must be in the file,** so the marking TA's can copy/paste and run your code to check that it works as intended.

You may add additional screenshots but I can't guarantee they will be looked at or contribute to your mark.

**Comment by lauramedlock** [comment]
@RayNele is it acceptable for us to submit the questions out of order? For example if you do Question B before Question A (if Question B helps you accomplish Question A more readily?).

**Comment by georgeamatyas** [comment]
Thanks for the response Ray. May I submit a bash script file instead of a pdf?

**Comment by joelostblom** [comment]
@SaraMati Could you answer regarding submitting a script instead of a PDF?

**Comment by RayNele** [comment]
@lauramedlock 

It's acceptable but not preferred. (Just makes things hard to mark, but your solution isn't incorrect) If you've already written it that way, just submit it as is. If it hasn't been written yet, try your best not to do them out of order. 

For this assignment, the TAs are looking through your code manually and checking for errors, but in the future I believe we will just run your code, in which case you can do whatever you want as long as you answer the question.

**Comment by RayNele** [comment]
@georgeamatyas The assignment can now be submitted on Quercus. The file type is unrestricted, which means you may submit any format of text file.

**Comment by RayNele** [comment]
@georgeamatyas  Sorry I missed your second question.

Short answer: yes that is correct.

Long answer: refer to #11
