### ISSUE TITLE
A4 Question 1D

### ISSUE THREAD

**Issue by Brendannigel** [BME1478H/Winter2020class#73]
Hello, is this correct or make sense for the output for question 1D? I am not sure if my code is wrong by when it said combine patient_summary to check_zeros helper function I assume we just add them together to create the new detect_problems function. But my output is neither true nor false 

def detect_problems(data):
    patient_summary + check_zeros
    return detect_problems
print(detect_problems)

**Output**: <function detect_problems at 0x000001BBFD229318>

**Comment by RayNele** [comment]
You can't combine two functions like that, not in real life, and not in python. 

Lets take a bit and think about how functions work in real life:

We can have functions `f(x) = 2x + 1` and `g(x) = 5x - 3` 

If we say `f + g`, that means nothing in terms of math, and coincidentally, doesn't mean anything in python either. However `f(x) + g(x)` can be valid, and so can `f(g(x))`, assuming that the inputs for the two functions are the same. 


You told python to return `detect_problems` and so it did. The function itself has no value, so python simply tells you it's an existing function.

**Comment by Brendannigel** [comment]
This is what I have tried and it is still not working:

def detect_problems(data):
    return check_problems(patient_summary(data, 'mean'))
print(detect_problems)

**output:** <function detect_problems at 0x0000025D51381B88>

I'm not sure why I have difficulty with this question. I have tried so many things but I cannot seem to find the one that works. Any help will be appreciated, thank you.

**Comment by Brendannigel** [comment]
sorry I had a typo in the code I sent, here it is: 

def detect_problems(data):
    return check_zeros(patient_summary(data, 'mean'))
print(detect_problems)

**output:** <function detect_problems at 0x0000025D527CB5E8>

**Comment by RayNele** [comment]
With print, you are calling on `detect_problems`, but it has no arguments. 

As far as I can see, your function is fine, but again: `f` on its own has no value. You need to call on `f(x)`. You're using `detect_problems` but there's no `data` argument.

**Comment by Brendannigel** [comment]
Ok that makes sense, so is it ok if I use dt instead of data since dt reads into the file "./data\\inflammation-01.csv"? here is the code: 

def detect_problems(dt):
    return check_zeros(patient_summary(dt, 'mean'))
print(detect_problems(dt))

**Output** False

I just want to make sure this is fine since the questions suggests using detect_problems(data). I want to make sure I won't loose marks for the code above

**Comment by RayNele** [comment]
Looks fine here. 

The name of the argument in a function does not actually matter, only when you're calling that function. 

You could replace the first two instances of dt in the function with literally any random letters and numbers, and as long as that last line uses `dt` it would still return false.
