### ISSUE TITLE
A7: Using 'errorbar' instead of 'ci' as a seaborn plot parameter

### ISSUE THREAD

**Issue by jtak09** [BME1478H/Winter2020class#738]
Hello, 

I'm following both the lesson and assignment instructions that specify we should use 'ci' as a parameter when plotting with seaborn to control the confidence interval: 

        ```python
        ax = sns.lineplot(x='year', y='child_mortality', data=world_data, ci='sd')

        ```
However, this generates a warning: 

/var/folders/0k/_tr3zw650tv_cg_306tr27_40000gn/T/ipykernel_21188/1020670418.py:3: FutureWarning: 
The `ci` parameter is deprecated. Use `errorbar='sd'` for the same effect.
  ax = sns.lineplot(x='year', y='child_mortality', data=world_data, ci='sd')

I understand that this message is being generated since the 'ci' parameter will be removed in a future version of the package, and 'errorbar' can be substituted to achieve the same result. 

I am confused as to why the lesson and assignment are instructing us to use a deprecated parameter. Wouldn't it be better to use 'errorbar'? Is there some functionality of 'ci' that I am missing? 

Furthermore, is it acceptable to use 'errorbar' instead of 'ci' in the assignment, or will marks be deducted for that? 

Thanks! 

PS. I am on macOS Ventura 13.5, python 3.11

**Comment by cancer-ray** [comment]
Hi Julia,

the assignments were created years ago, before deprecation of ci was
announced.

you can use either and it will be marked correct.

Best,

Ryan

**Comment by jtak09** [comment]
Thanks Ryan!
