### ISSUE TITLE
Assignment 7, Task 6

### ISSUE THREAD

**Issue by MDHermans** [BME1478H/Winter2020class#739]
During Task 4, I decided to reorder the categories to be more intuitive (low income -> high income) as described in the lecture. This was not listed as a requirement, but I thought it made the data look better. 

Now for Task 6, we're technically supposed to have an exact match, but I noticed that the assignment's version of the facets do not have this reordering (which I understand does not have any real effect besides colouring). Does this matter? Should I remove that reorder modification from earlier? Thanks!

**Comment by cancer-ray** [comment]
should be okay, just the order of the legend is different and the lines are
plotted in different colors.

**Comment by MDHermans** [comment]
Thanks for confirming, Ryan!
