### ISSUE TITLE
Assignment 5/Lesson 6 - Importance of script=sys.argv[0]

### ISSUE THREAD

**Issue by dtovbis** [BME1478H/Winter2020class#74]
What does this line actually do, and when is it necessary? I tried the assignment and my script seems to run whether or not I include that line.

**Comment by RayNele** [comment]
It doesn't do anything pertaining to the execution of that particular script, but if for whatever reason you needed the name of the script, it would be stored in `script`. 

I can't think of any other reason you'd use `sys.argv[0]` off the top of my head
