### ISSUE TITLE
Assignment 8, Unable to import gammas dataset using sns, ValueError: 'gammas' is not one of the example datasets

### ISSUE THREAD

**Issue by pkeerthi11** [BME1478H/Winter2020class#741]
When running the following line of code in assignment 8:

```
gammas = sns.load_dataset('gammas')
```
I get the following error:
```
ValueError: 'gammas' is not one of the example datasets
```
Testing available datasets using 
```
sns.get_dataset_names()
```
results in a list in which gammas is not listed, however there is 'fmri'. Should I use this dataset instead?

**Comment by cancer-ray** [comment]
#622 I think,
take a look at the previous issue as well

**Comment by pkeerthi11** [comment]
Looks good, thanks!
