### ISSUE TITLE
Assignment 10, Task 3(a)

### ISSUE THREAD

**Issue by MDHermans** [BME1478H/Winter2020class#747]
After running my code for question 3a, I seem to get the appropriate output, but with this error also.
![Screenshot 2023-11-24 at 15 16 47](https://github.com/BME1478H/Fall2022class/assets/59268737/8e1b91be-cdd5-42e5-9f1a-616b1ffa5ab6)

It does not seem to impact anything, so should this be ignored?

Thanks!

**Comment by cancer-ray** [comment]
ya ignore
