### ISSUE TITLE
A4 - Q2d Getting an Error Message

### ISSUE THREAD

**Issue by chowd505** [BME1478H/Winter2020class#76]
# TODO: modify this basic class as per the instructions above
class Experiment:
    study = 'arthritis'
    experimenter = 'Dr. Aria'
    def __init__(self,session_no):
        self.session_no = session_no
        self.data = None
        
    def add_data(self,fnames):
        self.data = np.loadtxt(fnames, delimiter = ',')
        
    def patient_summary(self,operation):
        ax = 1
        if operation == 'mean':
            summary_values = self.mean(axis=ax)
        elif operation == 'max':
            summary_values = self.max(axis=ax)
        else:
            summary_values = self.min(axis=ax)
        return summary_values

# TODO: move these lines around and indent as necessary to make it work again, it *should* find three files.

session_counter = 1 # initialize counter

for f in fnames:  # iterate over data files
    exp = Experiment(session_counter) # create an instance of our experiment and give it a session_no
    exp.add_data(f) # read in our data to our experiment
    values = exp.patient_summary("mean") # get our patient means
    if check_zeros(values): # check whether any 0s in our means
        print(f) # print filename
    session_counter += 1 # increment our counter to the next session number

![image](https://user-images.githubusercontent.com/59659816/74482845-4bf12a80-4e83-11ea-8f0c-c1c7389d17aa.png)

Not sure why I am getting this error message. please help

**Comment by RayNele** [comment]
Not sure if its related to your issue, but your method should be named `__init__`

If you could format your code with triple backticks and paste it here (``` before and after your code) I can take a better look.

**Comment by chowd505** [comment]
```class Experiment:
    study = 'arthritis'
    experimenter = 'Dr. Aria'
    def __init__(self,session_no):
        self.session_no = session_no
        self.data = None
        
    def add_data(self,fnames):
        self.data = np.loadtxt(fnames, delimiter = ',')
        
    def patient_summary(self,operation):
        ax = 1
        if operation == 'mean':
            summary_values = self.mean(axis=ax)
        elif operation == 'max':
            summary_values = self.max(axis=ax)
        else:
            summary_values = self.min(axis=ax)
        return summary_values```
```# TODO: move these lines around and indent as necessary to make it work again, it *should* find three files.

session_counter = 1 # initialize counter

for f in fnames:  # iterate over data files
    exp = Experiment(session_counter) # create an instance of our experiment and give it a session_no
    exp.add_data(f) # read in our data to our experiment
    values = exp.patient_summary("mean") # get our patient means
    if check_zeros(values): # check whether any 0s in our means
        print(f) # print filename
    session_counter += 1 # increment our counter to the next session number```

**Comment by chowd505** [comment]
> Not sure if its related to your issue, but your method should be named `__init__`
> 
> If you could format your code with triple backticks and paste it here (``` before and after your code) I can take a better look.


# TODO: modify this basic class as per the instructions above
```
class Experiment:
    study = 'arthritis'
    experimenter = 'Dr. Aria'
    def __init__(self,session_no):
        self.session_no = session_no
        self.data = None
        
    def add_data(self,fnames):
        dt = np.loadtxt(fnames, delimiter = ',')
        
    def patient_summary(self,operation):
        ax = 1
        if operation == 'mean':
            summary_values = self.mean(axis=ax)
        elif operation == 'max':
            summary_values = self.max(axis=ax)
        else:
            summary_values = self.min(axis=ax)
        return summary_values

# TODO: move these lines around and indent as necessary to make it work again, it *should* find three files.

session_counter = 1 # initialize counter

for f in fnames: # iterate over data files
    exp = Experiment(session_counter) # create an instance of our experiment and give it a session_no
    exp.add_data(f) # read in our data to our experiment
    values = exp.patient_summary("mean") # get our patient means
    if check_zeros(values): # check whether any 0s in our means
        print(f) # print filename
    session_counter += 1 # increment our counter to the next session number```


Can you help me fix the code. I am getting an error message and not sure how to fix it?

**Comment by RayNele** [comment]
Can you show how fnames was defined, and print it?

**Comment by chowd505** [comment]
![image](https://user-images.githubusercontent.com/59659816/74549557-d6866800-4f1d-11ea-86c8-220fdf19b44c.png)

**Comment by chowd505** [comment]
> Can you show how fnames was defined, and print it?

![image](https://user-images.githubusercontent.com/59659816/74549771-341ab480-4f1e-11ea-9774-708b0857ce18.png)

**Comment by RayNele** [comment]
Why do you only have one file there? 

Can you show me how it was defined?

**Comment by chowd505** [comment]
> Why do you only have one file there?
> 
> Can you show me how it was defined?

![image](https://user-images.githubusercontent.com/59659816/74551738-bc4e8900-4f21-11ea-8704-420de2c6bc01.png)

**Comment by RayNele** [comment]
Use the first position in the fnames instead of redefining it

**Comment by chowd505** [comment]
how should I do that?

I am not sure

**Comment by RayNele** [comment]
This was in the last assignment I believe. 

`fnames[0]`

**Comment by chowd505** [comment]
I made the change accordingly, but it does not resolve the problem of Q2d. 
I am still getting an error msg. 
![image](https://user-images.githubusercontent.com/59659816/74552768-f6b92580-4f23-11ea-906f-805c516825ea.png)

**Comment by chowd505** [comment]
> This was in the last assignment I believe.
> 
> `fnames[0]`

I made the change accordingly, but it does not resolve the problem of Q2d.
I am still getting an error msg.

![image](https://user-images.githubusercontent.com/59659816/74552811-0e90a980-4f24-11ea-9701-cb266beb6684.png)

**Comment by chowd505** [comment]
> This was in the last assignment I believe.
> 
> `fnames[0]`

![image](https://user-images.githubusercontent.com/59659816/74557911-38030280-4f2f-11ea-9d70-97ac6d5aae45.png)

**Comment by RayNele** [comment]
Working as intended there. You dont have a `mean` method in your class. Change the way you calculate mean.

**Comment by chowd505** [comment]
> Working as intended there. You dont have a `mean` method in your class. Change the way you calculate mean.

Isn't that the only way to calculate mean?

can you advise how I should calculate the mean in order to fix this error message.

**Comment by RayNele** [comment]
You can sum the values and divide by the number of total values. 

Also you are trying to calculate the sum of `self` which is not where the data is stored. The data is stored in`self.data`

**Comment by joelostblom** [comment]
Further comments can also be found in https://github.com/BME1478H/Winter2020class/issues/84 in case it is helpful to hear it explained in another way.
