### ISSUE TITLE
ImportError in Git Bash for import numpy

### ISSUE THREAD

**Issue by mwychan-BME** [BME1478H/Winter2020class#77]
I am trying to run the code in the Week 6 lesson. 

When I try to run sample code that includes `import numpy`  within the python script, I get the following error in the command line: 

> $ python ../code/stats_01.py inflammation-01.csv
> Traceback (most recent call last):
>   File "../code/stats_01.py", line 2, in <module>
>     import numpy
>   File "C:\Users\xx\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\__init__.py", line 140, in <module>
>     from . import _distributor_init
>   File "C:\Users\xx\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
>     from . import _mklinit
> ImportError: DLL load failed: The specified module could not be found.

I am running Windows 10. There were no errors with the earlier instructions for `import sys` or returning system values. Thanks.

**Comment by joelostblom** [comment]
Try reinstalling numpy. If that does not work, look into the solutions in these threads (sorry I can't be more specific, I have not seen this error before):

- https://stackoverflow.com/questions/36778066/importerror-dll-load-failed-when-importing-numpy-installed-in-conda-virtual-env
- https://github.com/ContinuumIO/anaconda-issues/issues/10628

**Comment by mwychan-BME** [comment]
I uninstalled/reinstalled numpy via command `conda uninstall numpy` and `conda install numpy`. Now when I run the same code that contains an import to numpy, I get the following error. I don't want to randomly mess up my computer entirely so I'm not sure which solution I'm supposed to try.

> $ python ../code/stats_01.py small-01.csv
> C:\Users\chanwi33\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
>   from . import _distributor_init
> Traceback (most recent call last):
>   File "C:\Users\chanwi33\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
>     from . import multiarray
>   File "C:\Users\chanwi33\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
>     from . import overrides
>   File "C:\Users\chanwi33\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
>     from numpy.core._multiarray_umath import (
> ImportError: DLL load failed: The specified module could not be found.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "../code/stats_01.py", line 2, in <module>
>     import numpy
>   File "C:\Users\chanwi33\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
>     from . import core
>   File "C:\Users\chanwi33\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\__init__.py", line 54, in <module>
>     raise ImportError(msg)
> ImportError:
> 
> IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
> 
> Importing the numpy c-extensions failed.
> - Try uninstalling and reinstalling numpy.
> - If you have already done that, then:
>   1. Check that you expected to use Python3.7 from "C:\Users\chanwi33\AppData\Local\Continuum\anaconda3\python.exe",
>      and that you have no directories in your PATH or PYTHONPATH that can
>      interfere with the Python and numpy version "1.18.1" you're trying to use.
>   2. If (1) looks fine, you can open a new issue at
>      https://github.com/numpy/numpy/issues.  Please include details on:
>      - how you installed Python
>      - how you installed numpy
>      - your operating system
>      - whether or not you have multiple versions of Python installed
>      - if you built from source, your compiler versions and ideally a build log
> 
> - If you're working with a numpy git repository, try `git clean -xdf`
>   (removes all files not under version control) and rebuild numpy.
> 
> Note: this error has many possible causes, so please don't comment on
> an existing issue about this - open a new one instead.
> 
> Original error was: DLL load failed: The specified module could not be found.

**Comment by RayNele** [comment]
So what @joelostblom said worked for a couple students in the class. Not sure why it's occuring, but basically the solution is:

`pip uninstall numpy`

`pip install numpy`

**Comment by RayNele** [comment]
Can you echo $PATH and paste the output here?

Chances are you need to add Anaconda3/Scripts to your path on windows 10. Sara sent out an email regarding this week 1.

**Comment by mwychan-BME** [comment]
Using `pip` to reinstall numpy looks like it has solved the issue. I am not getting an error with code that includes importing numpy. Thanks for the help.
