### ISSUE TITLE
Mac default python environment

### ISSUE THREAD

**Issue by moonj94** [BME1478H/Winter2020class#80]
I don't know what happened, but my default python environment changed to version 3.7.4 Clang 4.0.1. How do I change it back to conda?

update:

doing which python results in:
/Users/jaemoon/opt/anaconda3/bin/python

but when I run: 

python sys_version.py:   (week 6) I get

version is 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by joelostblom** [comment]
The Python version string does not necessarily look exactly as is shown in the lecture slide. Try typing just `python` and see if anaconda show up after "clang". This is how it looks on my system

```shell
# -VV is the same as sys.version
$ python -VV
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0]
```

```
$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

Note that "Clang" indicates which compiler has been used to built your version of Python and is not conflicting with your distribution being from Anaconda. In my case it is "GCC" instead.

**Comment by moonj94** [comment]
I see. But when I use Atom to do the lesson, the autofill options don't register numpy or sys or anything like that.

**Comment by joelostblom** [comment]
I don't use atom myself, but I believe that it should pick up your default python installation. So as long as this is conda (which it seems to be based on the output from `which python`), and you have installed numpy in you default conda environment, they should autocomplete in atom. If you are note using your default environment, you might need to first activate the conda environment and then launch atom from shell, [as described here](https://stackoverflow.com/questions/43207427/using-anaconda-environment-in-atom) (maybe give that a try in any case if it works better). Let me know the outcome of that, and if it does not work I can tag a couple of the other TAs who might have more experience with atom.

**Comment by moonj94** [comment]
I have a couple questions
- How do I get to anaconda terminal?
- How do I activate conda environment?

**Comment by joelostblom** [comment]
On macOS, use the standard terminal. When you open your terminal, does the prompt start with some text in parenthesis, e.g. `(base)`? If it doesn't, your default conda environment is not activating as it should.

If you have never changed environment, you should not need to worry about activating another one. Is it only autocomplete in atom that does not work? Can you run code that imports numpy? I'm just making sure this is a problem with atom only and not your installation in general.

**Comment by moonj94** [comment]
Yes, it does start with (base).

I think it's working normally now(?). certian things are autocompleting, but not exactly as desired. Will update when there's more salient information
