### ISSUE TITLE
A4 Question 1a - Getting no output

### ISSUE THREAD

**Issue by shobnams** [BME1478H/Winter2020class#83]
![Screenshot (268)](https://user-images.githubusercontent.com/59714722/74577055-79a9a280-4f5b-11ea-9897-e8005d219bff.png)

Hi. I am working on question 1 part a but I am not getting any output. I downloaded the zip data folder and the notebook file in the folder Assignment-4 which is under Desktop. Can anyone please let me know what I am doing wrong? Thank you!

**Comment by RayNele** [comment]
The path for your file is wrong. For absolute paths to work, you need to start at $HOME, which is denoted by a tilde `~`.

**Comment by shobnams** [comment]
Do you mean I need to write:
fnames = glob.glob("~./data/inflammation*.csv") 

Because I tried this too and I still don't get any output.

**Comment by RayNele** [comment]
If you can't get absolute paths to work, use `pwd` to find where the current working directory of your .ipynb file is right now, then use the relative path to navigate to your data folder. 

As for absolute paths, the Desktop folder is within your home folder. So `~/Desktop`

**Comment by shobnams** [comment]
Thank you. I got it.
