### ISSUE TITLE
Assignment 4 Question 2D

### ISSUE THREAD

**Issue by Brendannigel** [BME1478H/Winter2020class#84]
Hello, I understand that from part b the data is stored in self.data but I do not understand how to run the code in part d to get it to work. I says that there is not attribute called mean and I understand that "mean" was not defined in the other parts of the question. I just don't know how I can format the code to get it to read into self.data. Please help, thank you

```class Experiment:
    study = "arthritis"
    experimenter = "Dr. Aria"
    def __init__(self,session_no):
        self.session_no = session_no
        self.data = None
        
    def add_data (self,fnames):
        self.data = np.loadtxt(fnames, delimiter = ',')
        
    def patient_summary(self,operation):
        ax = 1
        if operation == 'mean':
            summary_values = self.mean(axis=ax)
        elif operation == 'max':
            summary_values = self.max(axis=ax)
        else:
            summary_values = self.min(axis=ax)
        return summary_values

session_counter = 1 # initialize counter

for f in fnames: # iterate over data files
    exp = Experiment(session_counter) # create an instance of our experiment and give it a session_no
    exp.add_data(f) # read in our data to our experiment
    values = exp.patient_summary("mean") # get our patient means
    
    if check_zeros(values): # check whether any 0s in our means
        print(f) # print filename
    session_counter += 1 # increment our counter to the next session number```

**Comment by Brendannigel** [comment]
**output** ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-131-044862e874d5> in <module>
      5     exp = Experiment(session_counter) # create an instance of our experiment and give it a session_no
      6     exp.add_data(f) # read in our data to our experiment
----> 7     values = exp.patient_summary("mean") # get our patient means
      8 
      9     if check_zeros(values): # check whether any 0s in our means

<ipython-input-130-e5f8c4f27194> in patient_summary(self, operation)
     13         ax = 1
     14         if operation == 'mean':
---> 15             summary_values = self.mean(axis=ax)
     16         elif operation == 'max':
     17             summary_values = self.max(axis=ax)

AttributeError: 'Experiment' object has no attribute 'mean'

**Comment by RayNele** [comment]
If you are trying to take the mean of the numbers stored in `self.data`, your code has to reflect that. 

For example, if you have a variable `a` and you want the mean of it, you would try `a.mean`

Thus, if `a` is an attribute of a class, you would do `self.a.mean`

similarly, `self.mean` does not give you the mean of `self.data`. I'll let you figure out the rest.

**Comment by t-christ1** [comment]
@RayNele I am also struggling with this question and just looked at your previous response in an attempt to fix my errors. I tried changing this code: 

>  # TODO: fill in the rest of the if(and or elif/else) statements

        if operation == 'mean':
            summary_values = self.mean(axis=ax)
        elif operation == 'max': 
            summary_values = self.max(axis=ax)
        else:
            summary_values = self.min(axis=ax)
        return summary_values    

to this: 

>  # TODO: fill in the rest of the if(and or elif/else) statements
        if operation == 'mean':
            summary_values = self.data.mean(axis=ax)
        elif operation == 'max': 
            summary_values = self.data.max(axis=ax)
        else:
            summary_values = self.data.min(axis=ax)
        return summary_values    

but that also didn't seem to work so maybe I interpreted your suggestion wrong. Are we supposed to be changing the syntax in question 2d? Because the instructions only say to move things around and changing indentations?

**Comment by RayNele** [comment]
@t-christ1 could you post the output of the code when you run it, along with the error you are receiving?

**Comment by t-christ1** [comment]
@RayNele Yes, so to give you my entire 'question 2' here is the first part: 

> # TODO: modify this basic class as per the instructions above

class Experiment:
    study = "arthritis"
    experimenter = "Dr. Aria" 
    
    def __init__(self,session_no):
        self.session_no = session_no
        self.data = None
    
    def add_data(self, fnames):
        dt=np.loadtxt(fnames, delimiter=',')
        
    def patient_summary(self, operation):
        ax = 1 #specify axis 0 or 1
    
    # TODO: fill in the rest of the if(and or elif/else) statements
        if operation == 'mean':
            summary_values = self.data.mean(axis=ax)
        elif operation == 'max': 
            summary_values = self.data.max(axis=ax)
        else:
            summary_values = self.data.min(axis=ax)
        return summary_values    

and here is part d: 

> # TODO: move these lines around and indent as necessary to make it work again, it *should* find three files.

session_counter = 1 # initialize counter

for f in fnames: # iterate over data files
    exp = Experiment(session_counter) # create an instance of our experiment and give it a session_no
    exp.add_data(f) # read in our data to our experiment
    values = exp.patient_summary('mean') # get our patient means
    
    if check_zeros(values): # check whether any 0s in our means
        print(f) # print filename
    session_counter += 1 # increment our counter to the next session number

and here is the error (i don't get any actual 'output')

> ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-105-916bb2dd9458> in <module>
      6     exp = Experiment(session_counter) # create an instance of our experiment and give it a session_no
      7     exp.add_data(f) # read in our data to our experiment
----> 8     values = exp.patient_summary('mean') # get our patient means
      9 
     10     if check_zeros(values): # check whether any 0s in our means

<ipython-input-104-3cc3ded0f04d> in patient_summary(self, operation)
     16     # TODO: fill in the rest of the if(and or elif/else) statements
     17         if operation == 'mean':
---> 18             summary_values = self.data.mean(axis=ax)
     19         elif operation == 'max':
     20             summary_values = self.data.max(axis=ax)

AttributeError: 'NoneType' object has no attribute 'mean'

**Comment by RayNele** [comment]
@t-christ1 yep, so if you look at the error, it's saying `self.data` is a NoneType variable, meaning it has nothing in it, thus you can't take a mean.

 So if you look at your `add_data` method, you've loaded the data into a variable `dt`, which promptly gets discarded shortly after without being used. 

Instead you want to store it in the `data` attribute of your class. 


Basically long story short, you're taking the mean of nothing, and you can fix this by putting something there. Namely in the `add_data` function. 

Let me know if what I've said was unclear and I can give a more thorough explanation.

**Comment by t-christ1** [comment]
Okay I think it worked! I changed dt to self.data so that i'm taking the mean of that now. 2d gave me the output of 3 files! It is extremely helpful to get validation when asking questions on here ("a small change needs to be made here___ to fix this problem" and "you interpreted my suggestion correctly") are very good responses to reassure me that I am moving in the right direction, so thank you for that!!

**Comment by RayNele** [comment]
@t-christ1 glad I could help

**Comment by Runner-H** [comment]
So I am having a similar problem and I have pasted my code below. It is telling me that 

> TypeError: __init__() missing 1 required positional argument: 'data' 

What don't I understand? 

`# TODO: modify this basic class as per the instructions above
class Experiment:
    
    study = "arthritis"
    experimenter = "Dr.Aria"
    
    def __init__(self,session_no, data):
        self.session_no = session_no
        self.data = None 
        
    def add_data(self, fnames):
        '''
        This function reads in a .csv file and stores the result in the .data attribute
        '''
        self.data = np.loadtxt(fnames, delimiter=',') 
        return self.data
          
    def patient_summary(self, operation):
        ''' Give a numpy array and an operation (mean, max or min) and the output is the operation value for a single patient (1 row = 1 patient)'''
        # specify that the operation will be performed accross each row
        ax = 1

        # TODO: fill in the rest of the if(and or elif/else) statements
        if operation == 'mean':
            summary_values = self.data.mean(axis=ax)
        elif operation == "max":
            summary_values = self.data.max(axis=ax)
        elif operation == "min": 
            summary_values = self.data.min(axis=ax)
        else:
            print("Operation invalid")
    
        return summary_values`

**Comment by RayNele** [comment]
@Runner-H so here, you've defined `__init__` to require an argument `data`. 

So that later, when the 
line `exp=Experiment(session_counter)` runs, it doesn't contain a second argument, so instantiate the object. 

In other words, if you have a math function `f(x,y) = 3x + 7y -9` you need both x and y to calculate the answer. But you've only given x.
