### ISSUE TITLE
Unsure if output is actually saving on .ipynb and .py files

### ISSUE THREAD

**Issue by t-christ1** [BME1478H/Winter2020class#87]
Hola, I've run all my code on Jupyter to produce the outputs and I've saved my assignment as .ipynb and .py files but when I open these on my computer they don't seem to show the output? I'm not sure if that's acceptable/if I can submit anyway - I just don't want to submit and be penalized if they don't show up for the TA marking. 

Thoughts?

**Comment by RayNele** [comment]
Should be fine. Only the ipynb should save cell output. Worst case, I can run your script again to produce the output before marking it.
