### ISSUE TITLE
Assignment 4 2d 'Experiment' object has no attribute 'mean'

### ISSUE THREAD

**Issue by DeMario96** [BME1478H/Winter2020class#89]
Getting the error code 'Experiment' object has no attribute 'mean'. Unsure where my code went wrong 
![Screen Shot 2020-02-16 at 4 05 25 PM](https://user-images.githubusercontent.com/59748627/74612794-ab934400-50d6-11ea-819b-9e78d2be4d2b.png)
![Screen Shot 2020-02-16 at 4 05 39 PM](https://user-images.githubusercontent.com/59748627/74612799-b0f08e80-50d6-11ea-9669-364eed04f499.png)

**Comment by RayNele** [comment]
Duplicate #84
