### ISSUE TITLE
Importance of quotes in bash

### ISSUE THREAD

**Issue by mwychan-BME** [BME1478H/Winter2020class#9]
1. What is the importance of quotes in bash? `grep CTNS genes.txt` was used in the first demonstration of the command to find the string CTNS. Later in the pipes demo, `grep 'VEGF' genes.txt` was used instead. It doesn't seem to make a difference.

2. What is the difference between single and double quotes in bash? `mkdir Project1` was first used to make a directory called Project1, but later used as `mkdir "dataset$num"` with double quotes in the loop challenge. Similarly, `echo The value of i` was used in loops but later `echo "The first argument is"`.

Is the single/double quote non-essential in bash to define a string? Thanks.

**Comment by RayNele** [comment]
Quotes are essential for strings containing more than one word. 

For example:

`mkdir project1 project2`

Creates two folders, one named project1 the other named project2. 


`mkdir 'project1 project2'`

Should create one folder named 'project1 project2', without the quotes, but with the space. 


This behaviour remains constant with other commands like `grep`

**Comment by mwychan-BME** [comment]
So for the examples listed in my original post, there isn't a purpose for having the quotes at all and it's just a formatting preference?

**Comment by RayNele** [comment]
Pretty much.

You can also place a `\` before spaces to indicate that it's a character in a name and not dividing two arguments.

In some cases a single word may also require single quotes, example shown in the following excerpt of the man pages for `find`;

>“paths must precede expression” error message
       $ find . -name *.c -print
       find: paths must precede expression
       find: possible unquoted pattern after predicate `-name'?

       This happens when the shell could expand the pattern *.c to more than
       one file name existing in the current directory, and passing the
       resulting file names in the command line to find like this:
       find . -name frcode.c locate.c word_io.c -print
       That command is of course not going to work, because the -name
       predicate allows exactly only one pattern as argument.  Instead of
       doing things this way, you should enclose the pattern in quotes or
       escape the wildcard, thus allowing find to use the pattern with the
       wildcard during the search for file name matching instead of file
       names expanded by the parent shell:
       $ find . -name '*.c' -print
       $ find . -name \*.c -print

**Comment by joelostblom** [comment]
For single versus double quotes, note that double quotes expand variables and other constructs inside them, while single quotes do not (which effectively means that most often you want to use double quotes). Note that this is specifically for bash, in languages like Python there is no difference. See https://stackoverflow.com/questions/6697753/difference-between-single-and-double-quotes-in-bash for more details.
