### ISSUE TITLE
unable to clone the git repository

### ISSUE THREAD

**Issue by Azzy-BME** [BME1478H/Winter2020class#92]
Hello,
Can you please help me understand and resolve why I'm getting this error message as I attempt to clone the git repository. 

![image](https://user-images.githubusercontent.com/47275119/74686145-941f8e00-519e-11ea-8504-5b3305648bc9.png)

**Comment by joelostblom** [comment]
Unfortunately, I have not seen this problem before. It sounds like [this solution](https://stackoverflow.com/a/52205053/2166823) should work, but if it doesn't, try one of the other ones on that page (probably still avoiding the top answer suggesting to use delete). If this doesn't work, try to get help from one of the TAs during the tutorial, cause it might to be easier to sit down next to someone for this one.

**Comment by joelostblom** [comment]
Were you able to resolve this issue?

**Comment by RayNele** [comment]
@joelostblom can confirm that your link is indeed the solution to the problem and homepath was not set correctly for whatever reason. Not sure if @Azzy-BME was able to get the solution working correctly

**Comment by Azzy-BME** [comment]
Thanks @joelostblom  and @RayNele . Yes, I changed the HOME and PATH and finally got it to work. Appreciate your help.
